/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ChatChatGUIDGet200ResponseDataParticipantsInner
 */
export interface ApiV1ChatChatGUIDGet200ResponseDataParticipantsInner {
    /**
     * 
     * @type {number}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataParticipantsInner
     */
    originalROWID?: number;
    /**
     * 
     * @type {Array<any>}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataParticipantsInner
     */
    messages?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataParticipantsInner
     */
    chats?: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataParticipantsInner
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataParticipantsInner
     */
    country?: string;
    /**
     * 
     * @type {any}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataParticipantsInner
     */
    uncanonicalizedId?: any;
}

/**
 * Check if a given object implements the ApiV1ChatChatGUIDGet200ResponseDataParticipantsInner interface.
 */
export function instanceOfApiV1ChatChatGUIDGet200ResponseDataParticipantsInner(value: object): boolean {
    return true;
}

export function ApiV1ChatChatGUIDGet200ResponseDataParticipantsInnerFromJSON(json: any): ApiV1ChatChatGUIDGet200ResponseDataParticipantsInner {
    return ApiV1ChatChatGUIDGet200ResponseDataParticipantsInnerFromJSONTyped(json, false);
}

export function ApiV1ChatChatGUIDGet200ResponseDataParticipantsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ChatChatGUIDGet200ResponseDataParticipantsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'originalROWID': json['originalROWID'] == null ? undefined : json['originalROWID'],
        'messages': json['messages'] == null ? undefined : json['messages'],
        'chats': json['chats'] == null ? undefined : json['chats'],
        'address': json['address'] == null ? undefined : json['address'],
        'country': json['country'] == null ? undefined : json['country'],
        'uncanonicalizedId': json['uncanonicalizedId'] == null ? undefined : json['uncanonicalizedId'],
    };
}

export function ApiV1ChatChatGUIDGet200ResponseDataParticipantsInnerToJSON(value?: ApiV1ChatChatGUIDGet200ResponseDataParticipantsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'originalROWID': value['originalROWID'],
        'messages': value['messages'],
        'chats': value['chats'],
        'address': value['address'],
        'country': value['country'],
        'uncanonicalizedId': value['uncanonicalizedId'],
    };
}

