/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ChatChatGUIDParticipantPostRequest
 */
export interface ApiV1ChatChatGUIDParticipantPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1ChatChatGUIDParticipantPostRequest
     */
    address?: string;
}

/**
 * Check if a given object implements the ApiV1ChatChatGUIDParticipantPostRequest interface.
 */
export function instanceOfApiV1ChatChatGUIDParticipantPostRequest(value: object): boolean {
    return true;
}

export function ApiV1ChatChatGUIDParticipantPostRequestFromJSON(json: any): ApiV1ChatChatGUIDParticipantPostRequest {
    return ApiV1ChatChatGUIDParticipantPostRequestFromJSONTyped(json, false);
}

export function ApiV1ChatChatGUIDParticipantPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ChatChatGUIDParticipantPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : json['address'],
    };
}

export function ApiV1ChatChatGUIDParticipantPostRequestToJSON(value?: ApiV1ChatChatGUIDParticipantPostRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'address': value['address'],
    };
}

