/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV1ChatChatGUIDMessageGet200ResponseDataInner } from './ApiV1ChatChatGUIDMessageGet200ResponseDataInner';
import {
    ApiV1ChatChatGUIDMessageGet200ResponseDataInnerFromJSON,
    ApiV1ChatChatGUIDMessageGet200ResponseDataInnerFromJSONTyped,
    ApiV1ChatChatGUIDMessageGet200ResponseDataInnerToJSON,
} from './ApiV1ChatChatGUIDMessageGet200ResponseDataInner';

/**
 * 
 * @export
 * @interface ApiV1ChatChatGUIDMessageGet200Response
 */
export interface ApiV1ChatChatGUIDMessageGet200Response {
    /**
     * 
     * @type {number}
     * @memberof ApiV1ChatChatGUIDMessageGet200Response
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ChatChatGUIDMessageGet200Response
     */
    message?: string;
    /**
     * 
     * @type {Array<ApiV1ChatChatGUIDMessageGet200ResponseDataInner>}
     * @memberof ApiV1ChatChatGUIDMessageGet200Response
     */
    data?: Array<ApiV1ChatChatGUIDMessageGet200ResponseDataInner>;
}

/**
 * Check if a given object implements the ApiV1ChatChatGUIDMessageGet200Response interface.
 */
export function instanceOfApiV1ChatChatGUIDMessageGet200Response(value: object): boolean {
    return true;
}

export function ApiV1ChatChatGUIDMessageGet200ResponseFromJSON(json: any): ApiV1ChatChatGUIDMessageGet200Response {
    return ApiV1ChatChatGUIDMessageGet200ResponseFromJSONTyped(json, false);
}

export function ApiV1ChatChatGUIDMessageGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ChatChatGUIDMessageGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ApiV1ChatChatGUIDMessageGet200ResponseDataInnerFromJSON)),
    };
}

export function ApiV1ChatChatGUIDMessageGet200ResponseToJSON(value?: ApiV1ChatChatGUIDMessageGet200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ApiV1ChatChatGUIDMessageGet200ResponseDataInnerToJSON)),
    };
}

