/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV1FcmClientGetDefaultResponseDataClientInnerServicesAppinviteService } from './ApiV1FcmClientGetDefaultResponseDataClientInnerServicesAppinviteService';
import {
    ApiV1FcmClientGetDefaultResponseDataClientInnerServicesAppinviteServiceFromJSON,
    ApiV1FcmClientGetDefaultResponseDataClientInnerServicesAppinviteServiceFromJSONTyped,
    ApiV1FcmClientGetDefaultResponseDataClientInnerServicesAppinviteServiceToJSON,
} from './ApiV1FcmClientGetDefaultResponseDataClientInnerServicesAppinviteService';

/**
 * 
 * @export
 * @interface ApiV1FcmClientGetDefaultResponseDataClientInnerServices
 */
export interface ApiV1FcmClientGetDefaultResponseDataClientInnerServices {
    /**
     * 
     * @type {ApiV1FcmClientGetDefaultResponseDataClientInnerServicesAppinviteService}
     * @memberof ApiV1FcmClientGetDefaultResponseDataClientInnerServices
     */
    appinviteService?: ApiV1FcmClientGetDefaultResponseDataClientInnerServicesAppinviteService;
}

/**
 * Check if a given object implements the ApiV1FcmClientGetDefaultResponseDataClientInnerServices interface.
 */
export function instanceOfApiV1FcmClientGetDefaultResponseDataClientInnerServices(value: object): boolean {
    return true;
}

export function ApiV1FcmClientGetDefaultResponseDataClientInnerServicesFromJSON(json: any): ApiV1FcmClientGetDefaultResponseDataClientInnerServices {
    return ApiV1FcmClientGetDefaultResponseDataClientInnerServicesFromJSONTyped(json, false);
}

export function ApiV1FcmClientGetDefaultResponseDataClientInnerServicesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1FcmClientGetDefaultResponseDataClientInnerServices {
    if (json == null) {
        return json;
    }
    return {
        
        'appinviteService': json['appinvite_service'] == null ? undefined : ApiV1FcmClientGetDefaultResponseDataClientInnerServicesAppinviteServiceFromJSON(json['appinvite_service']),
    };
}

export function ApiV1FcmClientGetDefaultResponseDataClientInnerServicesToJSON(value?: ApiV1FcmClientGetDefaultResponseDataClientInnerServices | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'appinvite_service': ApiV1FcmClientGetDefaultResponseDataClientInnerServicesAppinviteServiceToJSON(value['appinviteService']),
    };
}

