/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV1FcmClientGetDefaultResponseDataClientInnerOauthClientInner } from './ApiV1FcmClientGetDefaultResponseDataClientInnerOauthClientInner';
import {
    ApiV1FcmClientGetDefaultResponseDataClientInnerOauthClientInnerFromJSON,
    ApiV1FcmClientGetDefaultResponseDataClientInnerOauthClientInnerFromJSONTyped,
    ApiV1FcmClientGetDefaultResponseDataClientInnerOauthClientInnerToJSON,
} from './ApiV1FcmClientGetDefaultResponseDataClientInnerOauthClientInner';

/**
 * 
 * @export
 * @interface ApiV1FcmClientGetDefaultResponseDataClientInnerServicesAppinviteService
 */
export interface ApiV1FcmClientGetDefaultResponseDataClientInnerServicesAppinviteService {
    /**
     * 
     * @type {Array<ApiV1FcmClientGetDefaultResponseDataClientInnerOauthClientInner>}
     * @memberof ApiV1FcmClientGetDefaultResponseDataClientInnerServicesAppinviteService
     */
    otherPlatformOauthClient?: Array<ApiV1FcmClientGetDefaultResponseDataClientInnerOauthClientInner>;
}

/**
 * Check if a given object implements the ApiV1FcmClientGetDefaultResponseDataClientInnerServicesAppinviteService interface.
 */
export function instanceOfApiV1FcmClientGetDefaultResponseDataClientInnerServicesAppinviteService(value: object): boolean {
    return true;
}

export function ApiV1FcmClientGetDefaultResponseDataClientInnerServicesAppinviteServiceFromJSON(json: any): ApiV1FcmClientGetDefaultResponseDataClientInnerServicesAppinviteService {
    return ApiV1FcmClientGetDefaultResponseDataClientInnerServicesAppinviteServiceFromJSONTyped(json, false);
}

export function ApiV1FcmClientGetDefaultResponseDataClientInnerServicesAppinviteServiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1FcmClientGetDefaultResponseDataClientInnerServicesAppinviteService {
    if (json == null) {
        return json;
    }
    return {
        
        'otherPlatformOauthClient': json['other_platform_oauth_client'] == null ? undefined : ((json['other_platform_oauth_client'] as Array<any>).map(ApiV1FcmClientGetDefaultResponseDataClientInnerOauthClientInnerFromJSON)),
    };
}

export function ApiV1FcmClientGetDefaultResponseDataClientInnerServicesAppinviteServiceToJSON(value?: ApiV1FcmClientGetDefaultResponseDataClientInnerServicesAppinviteService | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'other_platform_oauth_client': value['otherPlatformOauthClient'] == null ? undefined : ((value['otherPlatformOauthClient'] as Array<any>).map(ApiV1FcmClientGetDefaultResponseDataClientInnerOauthClientInnerToJSON)),
    };
}

