/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ServerStatisticsMediaChatGet200ResponseDataInnerTotals
 */
export interface ApiV1ServerStatisticsMediaChatGet200ResponseDataInnerTotals {
    /**
     * 
     * @type {number}
     * @memberof ApiV1ServerStatisticsMediaChatGet200ResponseDataInnerTotals
     */
    images?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV1ServerStatisticsMediaChatGet200ResponseDataInnerTotals
     */
    videos?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV1ServerStatisticsMediaChatGet200ResponseDataInnerTotals
     */
    locations?: number;
}

/**
 * Check if a given object implements the ApiV1ServerStatisticsMediaChatGet200ResponseDataInnerTotals interface.
 */
export function instanceOfApiV1ServerStatisticsMediaChatGet200ResponseDataInnerTotals(value: object): boolean {
    return true;
}

export function ApiV1ServerStatisticsMediaChatGet200ResponseDataInnerTotalsFromJSON(json: any): ApiV1ServerStatisticsMediaChatGet200ResponseDataInnerTotals {
    return ApiV1ServerStatisticsMediaChatGet200ResponseDataInnerTotalsFromJSONTyped(json, false);
}

export function ApiV1ServerStatisticsMediaChatGet200ResponseDataInnerTotalsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ServerStatisticsMediaChatGet200ResponseDataInnerTotals {
    if (json == null) {
        return json;
    }
    return {
        
        'images': json['images'] == null ? undefined : json['images'],
        'videos': json['videos'] == null ? undefined : json['videos'],
        'locations': json['locations'] == null ? undefined : json['locations'],
    };
}

export function ApiV1ServerStatisticsMediaChatGet200ResponseDataInnerTotalsToJSON(value?: ApiV1ServerStatisticsMediaChatGet200ResponseDataInnerTotals | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'images': value['images'],
        'videos': value['videos'],
        'locations': value['locations'],
    };
}

