/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1MessageGUIDEditPostRequest
 */
export interface ApiV1MessageGUIDEditPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1MessageGUIDEditPostRequest
     */
    editedMessage?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1MessageGUIDEditPostRequest
     */
    backwardsCompatibilityMessage?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV1MessageGUIDEditPostRequest
     */
    partIndex?: number;
}

/**
 * Check if a given object implements the ApiV1MessageGUIDEditPostRequest interface.
 */
export function instanceOfApiV1MessageGUIDEditPostRequest(value: object): boolean {
    return true;
}

export function ApiV1MessageGUIDEditPostRequestFromJSON(json: any): ApiV1MessageGUIDEditPostRequest {
    return ApiV1MessageGUIDEditPostRequestFromJSONTyped(json, false);
}

export function ApiV1MessageGUIDEditPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1MessageGUIDEditPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'editedMessage': json['editedMessage'] == null ? undefined : json['editedMessage'],
        'backwardsCompatibilityMessage': json['backwardsCompatibilityMessage'] == null ? undefined : json['backwardsCompatibilityMessage'],
        'partIndex': json['partIndex'] == null ? undefined : json['partIndex'],
    };
}

export function ApiV1MessageGUIDEditPostRequestToJSON(value?: ApiV1MessageGUIDEditPostRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'editedMessage': value['editedMessage'],
        'backwardsCompatibilityMessage': value['backwardsCompatibilityMessage'],
        'partIndex': value['partIndex'],
    };
}

