/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfoAndroidClientInfo } from './ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfoAndroidClientInfo';
import {
    ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfoAndroidClientInfoFromJSON,
    ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfoAndroidClientInfoFromJSONTyped,
    ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfoAndroidClientInfoToJSON,
} from './ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfoAndroidClientInfo';

/**
 * 
 * @export
 * @interface ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfo
 */
export interface ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfo {
    /**
     * 
     * @type {string}
     * @memberof ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfo
     */
    mobilesdkAppId?: string;
    /**
     * 
     * @type {ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfoAndroidClientInfo}
     * @memberof ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfo
     */
    androidClientInfo?: ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfoAndroidClientInfo;
}

/**
 * Check if a given object implements the ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfo interface.
 */
export function instanceOfApiV1FcmClientGetDefaultResponseDataClientInnerClientInfo(value: object): boolean {
    return true;
}

export function ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfoFromJSON(json: any): ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfo {
    return ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfoFromJSONTyped(json, false);
}

export function ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'mobilesdkAppId': json['mobilesdk_app_id'] == null ? undefined : json['mobilesdk_app_id'],
        'androidClientInfo': json['android_client_info'] == null ? undefined : ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfoAndroidClientInfoFromJSON(json['android_client_info']),
    };
}

export function ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfoToJSON(value?: ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'mobilesdk_app_id': value['mobilesdkAppId'],
        'android_client_info': ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfoAndroidClientInfoToJSON(value['androidClientInfo']),
    };
}

