/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1FcmClientGetDefaultResponseDataProjectInfo
 */
export interface ApiV1FcmClientGetDefaultResponseDataProjectInfo {
    /**
     * 
     * @type {string}
     * @memberof ApiV1FcmClientGetDefaultResponseDataProjectInfo
     */
    projectNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1FcmClientGetDefaultResponseDataProjectInfo
     */
    firebaseUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1FcmClientGetDefaultResponseDataProjectInfo
     */
    projectId?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1FcmClientGetDefaultResponseDataProjectInfo
     */
    storageBucket?: string;
}

/**
 * Check if a given object implements the ApiV1FcmClientGetDefaultResponseDataProjectInfo interface.
 */
export function instanceOfApiV1FcmClientGetDefaultResponseDataProjectInfo(value: object): boolean {
    return true;
}

export function ApiV1FcmClientGetDefaultResponseDataProjectInfoFromJSON(json: any): ApiV1FcmClientGetDefaultResponseDataProjectInfo {
    return ApiV1FcmClientGetDefaultResponseDataProjectInfoFromJSONTyped(json, false);
}

export function ApiV1FcmClientGetDefaultResponseDataProjectInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1FcmClientGetDefaultResponseDataProjectInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'projectNumber': json['project_number'] == null ? undefined : json['project_number'],
        'firebaseUrl': json['firebase_url'] == null ? undefined : json['firebase_url'],
        'projectId': json['project_id'] == null ? undefined : json['project_id'],
        'storageBucket': json['storage_bucket'] == null ? undefined : json['storage_bucket'],
    };
}

export function ApiV1FcmClientGetDefaultResponseDataProjectInfoToJSON(value?: ApiV1FcmClientGetDefaultResponseDataProjectInfo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'project_number': value['projectNumber'],
        'firebase_url': value['firebaseUrl'],
        'project_id': value['projectId'],
        'storage_bucket': value['storageBucket'],
    };
}

