/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV1MessageMultipartPostRequestPartsInner } from './ApiV1MessageMultipartPostRequestPartsInner';
import {
    ApiV1MessageMultipartPostRequestPartsInnerFromJSON,
    ApiV1MessageMultipartPostRequestPartsInnerFromJSONTyped,
    ApiV1MessageMultipartPostRequestPartsInnerToJSON,
} from './ApiV1MessageMultipartPostRequestPartsInner';

/**
 * 
 * @export
 * @interface ApiV1MessageMultipartPostRequest
 */
export interface ApiV1MessageMultipartPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1MessageMultipartPostRequest
     */
    chatGuid?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1MessageMultipartPostRequest
     */
    subject?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1MessageMultipartPostRequest
     */
    effectId?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1MessageMultipartPostRequest
     */
    selectedMessageGuid?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV1MessageMultipartPostRequest
     */
    partIndex?: number;
    /**
     * 
     * @type {Array<ApiV1MessageMultipartPostRequestPartsInner>}
     * @memberof ApiV1MessageMultipartPostRequest
     */
    parts?: Array<ApiV1MessageMultipartPostRequestPartsInner>;
}

/**
 * Check if a given object implements the ApiV1MessageMultipartPostRequest interface.
 */
export function instanceOfApiV1MessageMultipartPostRequest(value: object): boolean {
    return true;
}

export function ApiV1MessageMultipartPostRequestFromJSON(json: any): ApiV1MessageMultipartPostRequest {
    return ApiV1MessageMultipartPostRequestFromJSONTyped(json, false);
}

export function ApiV1MessageMultipartPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1MessageMultipartPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'chatGuid': json['chatGuid'] == null ? undefined : json['chatGuid'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'effectId': json['effectId'] == null ? undefined : json['effectId'],
        'selectedMessageGuid': json['selectedMessageGuid'] == null ? undefined : json['selectedMessageGuid'],
        'partIndex': json['partIndex'] == null ? undefined : json['partIndex'],
        'parts': json['parts'] == null ? undefined : ((json['parts'] as Array<any>).map(ApiV1MessageMultipartPostRequestPartsInnerFromJSON)),
    };
}

export function ApiV1MessageMultipartPostRequestToJSON(value?: ApiV1MessageMultipartPostRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'chatGuid': value['chatGuid'],
        'subject': value['subject'],
        'effectId': value['effectId'],
        'selectedMessageGuid': value['selectedMessageGuid'],
        'partIndex': value['partIndex'],
        'parts': value['parts'] == null ? undefined : ((value['parts'] as Array<any>).map(ApiV1MessageMultipartPostRequestPartsInnerToJSON)),
    };
}

