/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV1FcmClientGetDefaultResponseDataClientInner } from './ApiV1FcmClientGetDefaultResponseDataClientInner';
import {
    ApiV1FcmClientGetDefaultResponseDataClientInnerFromJSON,
    ApiV1FcmClientGetDefaultResponseDataClientInnerFromJSONTyped,
    ApiV1FcmClientGetDefaultResponseDataClientInnerToJSON,
} from './ApiV1FcmClientGetDefaultResponseDataClientInner';
import type { ApiV1FcmClientGetDefaultResponseDataProjectInfo } from './ApiV1FcmClientGetDefaultResponseDataProjectInfo';
import {
    ApiV1FcmClientGetDefaultResponseDataProjectInfoFromJSON,
    ApiV1FcmClientGetDefaultResponseDataProjectInfoFromJSONTyped,
    ApiV1FcmClientGetDefaultResponseDataProjectInfoToJSON,
} from './ApiV1FcmClientGetDefaultResponseDataProjectInfo';

/**
 * 
 * @export
 * @interface ApiV1FcmClientGetDefaultResponseData
 */
export interface ApiV1FcmClientGetDefaultResponseData {
    /**
     * 
     * @type {ApiV1FcmClientGetDefaultResponseDataProjectInfo}
     * @memberof ApiV1FcmClientGetDefaultResponseData
     */
    projectInfo?: ApiV1FcmClientGetDefaultResponseDataProjectInfo;
    /**
     * 
     * @type {Array<ApiV1FcmClientGetDefaultResponseDataClientInner>}
     * @memberof ApiV1FcmClientGetDefaultResponseData
     */
    client?: Array<ApiV1FcmClientGetDefaultResponseDataClientInner>;
    /**
     * 
     * @type {string}
     * @memberof ApiV1FcmClientGetDefaultResponseData
     */
    configurationVersion?: string;
}

/**
 * Check if a given object implements the ApiV1FcmClientGetDefaultResponseData interface.
 */
export function instanceOfApiV1FcmClientGetDefaultResponseData(value: object): boolean {
    return true;
}

export function ApiV1FcmClientGetDefaultResponseDataFromJSON(json: any): ApiV1FcmClientGetDefaultResponseData {
    return ApiV1FcmClientGetDefaultResponseDataFromJSONTyped(json, false);
}

export function ApiV1FcmClientGetDefaultResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1FcmClientGetDefaultResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'projectInfo': json['project_info'] == null ? undefined : ApiV1FcmClientGetDefaultResponseDataProjectInfoFromJSON(json['project_info']),
        'client': json['client'] == null ? undefined : ((json['client'] as Array<any>).map(ApiV1FcmClientGetDefaultResponseDataClientInnerFromJSON)),
        'configurationVersion': json['configuration_version'] == null ? undefined : json['configuration_version'],
    };
}

export function ApiV1FcmClientGetDefaultResponseDataToJSON(value?: ApiV1FcmClientGetDefaultResponseData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'project_info': ApiV1FcmClientGetDefaultResponseDataProjectInfoToJSON(value['projectInfo']),
        'client': value['client'] == null ? undefined : ((value['client'] as Array<any>).map(ApiV1FcmClientGetDefaultResponseDataClientInnerToJSON)),
        'configuration_version': value['configurationVersion'],
    };
}

