/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInner
 */
export interface ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInner {
    /**
     * 
     * @type {number}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInner
     */
    originalROWID?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInner
     */
    guid?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInner
     */
    participants?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInner
     */
    messages?: Array<any>;
    /**
     * 
     * @type {number}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInner
     */
    style?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInner
     */
    chatIdentifier?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInner
     */
    isArchived?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInner
     */
    isFiltered?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInner
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInner
     */
    groupId?: string;
}

/**
 * Check if a given object implements the ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInner interface.
 */
export function instanceOfApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInner(value: object): boolean {
    return true;
}

export function ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInnerFromJSON(json: any): ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInner {
    return ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInnerFromJSONTyped(json, false);
}

export function ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'originalROWID': json['originalROWID'] == null ? undefined : json['originalROWID'],
        'guid': json['guid'] == null ? undefined : json['guid'],
        'participants': json['participants'] == null ? undefined : json['participants'],
        'messages': json['messages'] == null ? undefined : json['messages'],
        'style': json['style'] == null ? undefined : json['style'],
        'chatIdentifier': json['chatIdentifier'] == null ? undefined : json['chatIdentifier'],
        'isArchived': json['isArchived'] == null ? undefined : json['isArchived'],
        'isFiltered': json['isFiltered'] == null ? undefined : json['isFiltered'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'groupId': json['groupId'] == null ? undefined : json['groupId'],
    };
}

export function ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInnerToJSON(value?: ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'originalROWID': value['originalROWID'],
        'guid': value['guid'],
        'participants': value['participants'],
        'messages': value['messages'],
        'style': value['style'],
        'chatIdentifier': value['chatIdentifier'],
        'isArchived': value['isArchived'],
        'isFiltered': value['isFiltered'],
        'displayName': value['displayName'],
        'groupId': value['groupId'],
    };
}

