/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ChatQueryPostRequest
 */
export interface ApiV1ChatQueryPostRequest {
    /**
     * 
     * @type {number}
     * @memberof ApiV1ChatQueryPostRequest
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV1ChatQueryPostRequest
     */
    offset?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiV1ChatQueryPostRequest
     */
    _with?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ChatQueryPostRequest
     */
    sort?: string;
}

/**
 * Check if a given object implements the ApiV1ChatQueryPostRequest interface.
 */
export function instanceOfApiV1ChatQueryPostRequest(value: object): boolean {
    return true;
}

export function ApiV1ChatQueryPostRequestFromJSON(json: any): ApiV1ChatQueryPostRequest {
    return ApiV1ChatQueryPostRequestFromJSONTyped(json, false);
}

export function ApiV1ChatQueryPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ChatQueryPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        '_with': json['with'] == null ? undefined : json['with'],
        'sort': json['sort'] == null ? undefined : json['sort'],
    };
}

export function ApiV1ChatQueryPostRequestToJSON(value?: ApiV1ChatQueryPostRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'limit': value['limit'],
        'offset': value['offset'],
        'with': value['_with'],
        'sort': value['sort'],
    };
}

