/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ServerAlertReadPostRequest
 */
export interface ApiV1ServerAlertReadPostRequest {
    /**
     * 
     * @type {Array<any>}
     * @memberof ApiV1ServerAlertReadPostRequest
     */
    ids?: Array<any>;
}

/**
 * Check if a given object implements the ApiV1ServerAlertReadPostRequest interface.
 */
export function instanceOfApiV1ServerAlertReadPostRequest(value: object): boolean {
    return true;
}

export function ApiV1ServerAlertReadPostRequestFromJSON(json: any): ApiV1ServerAlertReadPostRequest {
    return ApiV1ServerAlertReadPostRequestFromJSONTyped(json, false);
}

export function ApiV1ServerAlertReadPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ServerAlertReadPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'] == null ? undefined : json['ids'],
    };
}

export function ApiV1ServerAlertReadPostRequestToJSON(value?: ApiV1ServerAlertReadPostRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ids': value['ids'],
    };
}

