/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV1ServerStatisticsMediaChatGet200ResponseDataInnerTotals } from './ApiV1ServerStatisticsMediaChatGet200ResponseDataInnerTotals';
import {
    ApiV1ServerStatisticsMediaChatGet200ResponseDataInnerTotalsFromJSON,
    ApiV1ServerStatisticsMediaChatGet200ResponseDataInnerTotalsFromJSONTyped,
    ApiV1ServerStatisticsMediaChatGet200ResponseDataInnerTotalsToJSON,
} from './ApiV1ServerStatisticsMediaChatGet200ResponseDataInnerTotals';

/**
 * 
 * @export
 * @interface ApiV1ServerStatisticsMediaChatGet200ResponseDataInner
 */
export interface ApiV1ServerStatisticsMediaChatGet200ResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof ApiV1ServerStatisticsMediaChatGet200ResponseDataInner
     */
    chatGuid?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ServerStatisticsMediaChatGet200ResponseDataInner
     */
    groupName?: string;
    /**
     * 
     * @type {ApiV1ServerStatisticsMediaChatGet200ResponseDataInnerTotals}
     * @memberof ApiV1ServerStatisticsMediaChatGet200ResponseDataInner
     */
    totals?: ApiV1ServerStatisticsMediaChatGet200ResponseDataInnerTotals;
}

/**
 * Check if a given object implements the ApiV1ServerStatisticsMediaChatGet200ResponseDataInner interface.
 */
export function instanceOfApiV1ServerStatisticsMediaChatGet200ResponseDataInner(value: object): boolean {
    return true;
}

export function ApiV1ServerStatisticsMediaChatGet200ResponseDataInnerFromJSON(json: any): ApiV1ServerStatisticsMediaChatGet200ResponseDataInner {
    return ApiV1ServerStatisticsMediaChatGet200ResponseDataInnerFromJSONTyped(json, false);
}

export function ApiV1ServerStatisticsMediaChatGet200ResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ServerStatisticsMediaChatGet200ResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'chatGuid': json['chatGuid'] == null ? undefined : json['chatGuid'],
        'groupName': json['groupName'] == null ? undefined : json['groupName'],
        'totals': json['totals'] == null ? undefined : ApiV1ServerStatisticsMediaChatGet200ResponseDataInnerTotalsFromJSON(json['totals']),
    };
}

export function ApiV1ServerStatisticsMediaChatGet200ResponseDataInnerToJSON(value?: ApiV1ServerStatisticsMediaChatGet200ResponseDataInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'chatGuid': value['chatGuid'],
        'groupName': value['groupName'],
        'totals': ApiV1ServerStatisticsMediaChatGet200ResponseDataInnerTotalsToJSON(value['totals']),
    };
}

