/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV1FcmClientGetDefaultResponseDataClientInnerApiKeyInner } from './ApiV1FcmClientGetDefaultResponseDataClientInnerApiKeyInner';
import {
    ApiV1FcmClientGetDefaultResponseDataClientInnerApiKeyInnerFromJSON,
    ApiV1FcmClientGetDefaultResponseDataClientInnerApiKeyInnerFromJSONTyped,
    ApiV1FcmClientGetDefaultResponseDataClientInnerApiKeyInnerToJSON,
} from './ApiV1FcmClientGetDefaultResponseDataClientInnerApiKeyInner';
import type { ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfo } from './ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfo';
import {
    ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfoFromJSON,
    ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfoFromJSONTyped,
    ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfoToJSON,
} from './ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfo';
import type { ApiV1FcmClientGetDefaultResponseDataClientInnerOauthClientInner } from './ApiV1FcmClientGetDefaultResponseDataClientInnerOauthClientInner';
import {
    ApiV1FcmClientGetDefaultResponseDataClientInnerOauthClientInnerFromJSON,
    ApiV1FcmClientGetDefaultResponseDataClientInnerOauthClientInnerFromJSONTyped,
    ApiV1FcmClientGetDefaultResponseDataClientInnerOauthClientInnerToJSON,
} from './ApiV1FcmClientGetDefaultResponseDataClientInnerOauthClientInner';
import type { ApiV1FcmClientGetDefaultResponseDataClientInnerServices } from './ApiV1FcmClientGetDefaultResponseDataClientInnerServices';
import {
    ApiV1FcmClientGetDefaultResponseDataClientInnerServicesFromJSON,
    ApiV1FcmClientGetDefaultResponseDataClientInnerServicesFromJSONTyped,
    ApiV1FcmClientGetDefaultResponseDataClientInnerServicesToJSON,
} from './ApiV1FcmClientGetDefaultResponseDataClientInnerServices';

/**
 * 
 * @export
 * @interface ApiV1FcmClientGetDefaultResponseDataClientInner
 */
export interface ApiV1FcmClientGetDefaultResponseDataClientInner {
    /**
     * 
     * @type {ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfo}
     * @memberof ApiV1FcmClientGetDefaultResponseDataClientInner
     */
    clientInfo?: ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfo;
    /**
     * 
     * @type {Array<ApiV1FcmClientGetDefaultResponseDataClientInnerOauthClientInner>}
     * @memberof ApiV1FcmClientGetDefaultResponseDataClientInner
     */
    oauthClient?: Array<ApiV1FcmClientGetDefaultResponseDataClientInnerOauthClientInner>;
    /**
     * 
     * @type {Array<ApiV1FcmClientGetDefaultResponseDataClientInnerApiKeyInner>}
     * @memberof ApiV1FcmClientGetDefaultResponseDataClientInner
     */
    apiKey?: Array<ApiV1FcmClientGetDefaultResponseDataClientInnerApiKeyInner>;
    /**
     * 
     * @type {ApiV1FcmClientGetDefaultResponseDataClientInnerServices}
     * @memberof ApiV1FcmClientGetDefaultResponseDataClientInner
     */
    services?: ApiV1FcmClientGetDefaultResponseDataClientInnerServices;
}

/**
 * Check if a given object implements the ApiV1FcmClientGetDefaultResponseDataClientInner interface.
 */
export function instanceOfApiV1FcmClientGetDefaultResponseDataClientInner(value: object): boolean {
    return true;
}

export function ApiV1FcmClientGetDefaultResponseDataClientInnerFromJSON(json: any): ApiV1FcmClientGetDefaultResponseDataClientInner {
    return ApiV1FcmClientGetDefaultResponseDataClientInnerFromJSONTyped(json, false);
}

export function ApiV1FcmClientGetDefaultResponseDataClientInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1FcmClientGetDefaultResponseDataClientInner {
    if (json == null) {
        return json;
    }
    return {
        
        'clientInfo': json['client_info'] == null ? undefined : ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfoFromJSON(json['client_info']),
        'oauthClient': json['oauth_client'] == null ? undefined : ((json['oauth_client'] as Array<any>).map(ApiV1FcmClientGetDefaultResponseDataClientInnerOauthClientInnerFromJSON)),
        'apiKey': json['api_key'] == null ? undefined : ((json['api_key'] as Array<any>).map(ApiV1FcmClientGetDefaultResponseDataClientInnerApiKeyInnerFromJSON)),
        'services': json['services'] == null ? undefined : ApiV1FcmClientGetDefaultResponseDataClientInnerServicesFromJSON(json['services']),
    };
}

export function ApiV1FcmClientGetDefaultResponseDataClientInnerToJSON(value?: ApiV1FcmClientGetDefaultResponseDataClientInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'client_info': ApiV1FcmClientGetDefaultResponseDataClientInnerClientInfoToJSON(value['clientInfo']),
        'oauth_client': value['oauthClient'] == null ? undefined : ((value['oauthClient'] as Array<any>).map(ApiV1FcmClientGetDefaultResponseDataClientInnerOauthClientInnerToJSON)),
        'api_key': value['apiKey'] == null ? undefined : ((value['apiKey'] as Array<any>).map(ApiV1FcmClientGetDefaultResponseDataClientInnerApiKeyInnerToJSON)),
        'services': ApiV1FcmClientGetDefaultResponseDataClientInnerServicesToJSON(value['services']),
    };
}

