/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1MessageSchedulePostRequestPayload
 */
export interface ApiV1MessageSchedulePostRequestPayload {
    /**
     * 
     * @type {string}
     * @memberof ApiV1MessageSchedulePostRequestPayload
     */
    chatGuid?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1MessageSchedulePostRequestPayload
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1MessageSchedulePostRequestPayload
     */
    method?: string;
}

/**
 * Check if a given object implements the ApiV1MessageSchedulePostRequestPayload interface.
 */
export function instanceOfApiV1MessageSchedulePostRequestPayload(value: object): boolean {
    return true;
}

export function ApiV1MessageSchedulePostRequestPayloadFromJSON(json: any): ApiV1MessageSchedulePostRequestPayload {
    return ApiV1MessageSchedulePostRequestPayloadFromJSONTyped(json, false);
}

export function ApiV1MessageSchedulePostRequestPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1MessageSchedulePostRequestPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'chatGuid': json['chatGuid'] == null ? undefined : json['chatGuid'],
        'message': json['message'] == null ? undefined : json['message'],
        'method': json['method'] == null ? undefined : json['method'],
    };
}

export function ApiV1MessageSchedulePostRequestPayloadToJSON(value?: ApiV1MessageSchedulePostRequestPayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'chatGuid': value['chatGuid'],
        'message': value['message'],
        'method': value['method'],
    };
}

