/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInner } from './ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInner';
import {
    ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInnerFromJSON,
    ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInnerFromJSONTyped,
    ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInnerToJSON,
} from './ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInner';

/**
 * 
 * @export
 * @interface ApiV1ChatChatGUIDGet200ResponseDataLastMessage
 */
export interface ApiV1ChatChatGUIDGet200ResponseDataLastMessage {
    /**
     * 
     * @type {number}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    originalROWID?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    guid?: string;
    /**
     * 
     * @type {any}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    text?: any;
    /**
     * 
     * @type {any}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    handle?: any;
    /**
     * 
     * @type {number}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    handleId?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    otherHandle?: number;
    /**
     * 
     * @type {Array<ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInner>}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    chats?: Array<ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInner>;
    /**
     * 
     * @type {Array<any>}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    attachments?: Array<any>;
    /**
     * 
     * @type {any}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    subject?: any;
    /**
     * 
     * @type {any}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    country?: any;
    /**
     * 
     * @type {number}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    error?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    dateCreated?: number;
    /**
     * 
     * @type {any}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    dateRead?: any;
    /**
     * 
     * @type {any}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    dateDelivered?: any;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    isFromMe?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    isDelayed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    isAutoReply?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    isSystemMessage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    isServiceMessage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    isForward?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    isArchived?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    cacheRoomnames?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    isAudioMessage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    hasDdResults?: boolean;
    /**
     * 
     * @type {any}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    datePlayed?: any;
    /**
     * 
     * @type {number}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    itemType?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    groupTitle?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    groupActionType?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    isExpired?: boolean;
    /**
     * 
     * @type {any}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    balloonBundleId?: any;
    /**
     * 
     * @type {any}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    associatedMessageGuid?: any;
    /**
     * 
     * @type {any}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    associatedMessageType?: any;
    /**
     * 
     * @type {any}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    expressiveSendStyleId?: any;
    /**
     * 
     * @type {any}
     * @memberof ApiV1ChatChatGUIDGet200ResponseDataLastMessage
     */
    timeExpressiveSendStyleId?: any;
}

/**
 * Check if a given object implements the ApiV1ChatChatGUIDGet200ResponseDataLastMessage interface.
 */
export function instanceOfApiV1ChatChatGUIDGet200ResponseDataLastMessage(value: object): boolean {
    return true;
}

export function ApiV1ChatChatGUIDGet200ResponseDataLastMessageFromJSON(json: any): ApiV1ChatChatGUIDGet200ResponseDataLastMessage {
    return ApiV1ChatChatGUIDGet200ResponseDataLastMessageFromJSONTyped(json, false);
}

export function ApiV1ChatChatGUIDGet200ResponseDataLastMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ChatChatGUIDGet200ResponseDataLastMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'originalROWID': json['originalROWID'] == null ? undefined : json['originalROWID'],
        'guid': json['guid'] == null ? undefined : json['guid'],
        'text': json['text'] == null ? undefined : json['text'],
        'handle': json['handle'] == null ? undefined : json['handle'],
        'handleId': json['handleId'] == null ? undefined : json['handleId'],
        'otherHandle': json['otherHandle'] == null ? undefined : json['otherHandle'],
        'chats': json['chats'] == null ? undefined : ((json['chats'] as Array<any>).map(ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInnerFromJSON)),
        'attachments': json['attachments'] == null ? undefined : json['attachments'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'country': json['country'] == null ? undefined : json['country'],
        'error': json['error'] == null ? undefined : json['error'],
        'dateCreated': json['dateCreated'] == null ? undefined : json['dateCreated'],
        'dateRead': json['dateRead'] == null ? undefined : json['dateRead'],
        'dateDelivered': json['dateDelivered'] == null ? undefined : json['dateDelivered'],
        'isFromMe': json['isFromMe'] == null ? undefined : json['isFromMe'],
        'isDelayed': json['isDelayed'] == null ? undefined : json['isDelayed'],
        'isAutoReply': json['isAutoReply'] == null ? undefined : json['isAutoReply'],
        'isSystemMessage': json['isSystemMessage'] == null ? undefined : json['isSystemMessage'],
        'isServiceMessage': json['isServiceMessage'] == null ? undefined : json['isServiceMessage'],
        'isForward': json['isForward'] == null ? undefined : json['isForward'],
        'isArchived': json['isArchived'] == null ? undefined : json['isArchived'],
        'cacheRoomnames': json['cacheRoomnames'] == null ? undefined : json['cacheRoomnames'],
        'isAudioMessage': json['isAudioMessage'] == null ? undefined : json['isAudioMessage'],
        'hasDdResults': json['hasDdResults'] == null ? undefined : json['hasDdResults'],
        'datePlayed': json['datePlayed'] == null ? undefined : json['datePlayed'],
        'itemType': json['itemType'] == null ? undefined : json['itemType'],
        'groupTitle': json['groupTitle'] == null ? undefined : json['groupTitle'],
        'groupActionType': json['groupActionType'] == null ? undefined : json['groupActionType'],
        'isExpired': json['isExpired'] == null ? undefined : json['isExpired'],
        'balloonBundleId': json['balloonBundleId'] == null ? undefined : json['balloonBundleId'],
        'associatedMessageGuid': json['associatedMessageGuid'] == null ? undefined : json['associatedMessageGuid'],
        'associatedMessageType': json['associatedMessageType'] == null ? undefined : json['associatedMessageType'],
        'expressiveSendStyleId': json['expressiveSendStyleId'] == null ? undefined : json['expressiveSendStyleId'],
        'timeExpressiveSendStyleId': json['timeExpressiveSendStyleId'] == null ? undefined : json['timeExpressiveSendStyleId'],
    };
}

export function ApiV1ChatChatGUIDGet200ResponseDataLastMessageToJSON(value?: ApiV1ChatChatGUIDGet200ResponseDataLastMessage | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'originalROWID': value['originalROWID'],
        'guid': value['guid'],
        'text': value['text'],
        'handle': value['handle'],
        'handleId': value['handleId'],
        'otherHandle': value['otherHandle'],
        'chats': value['chats'] == null ? undefined : ((value['chats'] as Array<any>).map(ApiV1ChatChatGUIDGet200ResponseDataLastMessageChatsInnerToJSON)),
        'attachments': value['attachments'],
        'subject': value['subject'],
        'country': value['country'],
        'error': value['error'],
        'dateCreated': value['dateCreated'],
        'dateRead': value['dateRead'],
        'dateDelivered': value['dateDelivered'],
        'isFromMe': value['isFromMe'],
        'isDelayed': value['isDelayed'],
        'isAutoReply': value['isAutoReply'],
        'isSystemMessage': value['isSystemMessage'],
        'isServiceMessage': value['isServiceMessage'],
        'isForward': value['isForward'],
        'isArchived': value['isArchived'],
        'cacheRoomnames': value['cacheRoomnames'],
        'isAudioMessage': value['isAudioMessage'],
        'hasDdResults': value['hasDdResults'],
        'datePlayed': value['datePlayed'],
        'itemType': value['itemType'],
        'groupTitle': value['groupTitle'],
        'groupActionType': value['groupActionType'],
        'isExpired': value['isExpired'],
        'balloonBundleId': value['balloonBundleId'],
        'associatedMessageGuid': value['associatedMessageGuid'],
        'associatedMessageType': value['associatedMessageType'],
        'expressiveSendStyleId': value['expressiveSendStyleId'],
        'timeExpressiveSendStyleId': value['timeExpressiveSendStyleId'],
    };
}

