/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ChatChatGUIDPutRequest
 */
export interface ApiV1ChatChatGUIDPutRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1ChatChatGUIDPutRequest
     */
    displayName?: string;
}

/**
 * Check if a given object implements the ApiV1ChatChatGUIDPutRequest interface.
 */
export function instanceOfApiV1ChatChatGUIDPutRequest(value: object): boolean {
    return true;
}

export function ApiV1ChatChatGUIDPutRequestFromJSON(json: any): ApiV1ChatChatGUIDPutRequest {
    return ApiV1ChatChatGUIDPutRequestFromJSONTyped(json, false);
}

export function ApiV1ChatChatGUIDPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ChatChatGUIDPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
    };
}

export function ApiV1ChatChatGUIDPutRequestToJSON(value?: ApiV1ChatChatGUIDPutRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'displayName': value['displayName'],
    };
}

