/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ServerStatisticsTotalsGet200ResponseData
 */
export interface ApiV1ServerStatisticsTotalsGet200ResponseData {
    /**
     * 
     * @type {number}
     * @memberof ApiV1ServerStatisticsTotalsGet200ResponseData
     */
    handles?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV1ServerStatisticsTotalsGet200ResponseData
     */
    messages?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV1ServerStatisticsTotalsGet200ResponseData
     */
    chats?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV1ServerStatisticsTotalsGet200ResponseData
     */
    attachments?: number;
}

/**
 * Check if a given object implements the ApiV1ServerStatisticsTotalsGet200ResponseData interface.
 */
export function instanceOfApiV1ServerStatisticsTotalsGet200ResponseData(value: object): boolean {
    return true;
}

export function ApiV1ServerStatisticsTotalsGet200ResponseDataFromJSON(json: any): ApiV1ServerStatisticsTotalsGet200ResponseData {
    return ApiV1ServerStatisticsTotalsGet200ResponseDataFromJSONTyped(json, false);
}

export function ApiV1ServerStatisticsTotalsGet200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ServerStatisticsTotalsGet200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'handles': json['handles'] == null ? undefined : json['handles'],
        'messages': json['messages'] == null ? undefined : json['messages'],
        'chats': json['chats'] == null ? undefined : json['chats'],
        'attachments': json['attachments'] == null ? undefined : json['attachments'],
    };
}

export function ApiV1ServerStatisticsTotalsGet200ResponseDataToJSON(value?: ApiV1ServerStatisticsTotalsGet200ResponseData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'handles': value['handles'],
        'messages': value['messages'],
        'chats': value['chats'],
        'attachments': value['attachments'],
    };
}

