/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV1FcmClientGetDefaultResponseData } from './ApiV1FcmClientGetDefaultResponseData';
import {
    ApiV1FcmClientGetDefaultResponseDataFromJSON,
    ApiV1FcmClientGetDefaultResponseDataFromJSONTyped,
    ApiV1FcmClientGetDefaultResponseDataToJSON,
} from './ApiV1FcmClientGetDefaultResponseData';

/**
 * 
 * @export
 * @interface ApiV1FcmClientGetDefaultResponse
 */
export interface ApiV1FcmClientGetDefaultResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiV1FcmClientGetDefaultResponse
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1FcmClientGetDefaultResponse
     */
    message?: string;
    /**
     * 
     * @type {ApiV1FcmClientGetDefaultResponseData}
     * @memberof ApiV1FcmClientGetDefaultResponse
     */
    data?: ApiV1FcmClientGetDefaultResponseData;
}

/**
 * Check if a given object implements the ApiV1FcmClientGetDefaultResponse interface.
 */
export function instanceOfApiV1FcmClientGetDefaultResponse(value: object): boolean {
    return true;
}

export function ApiV1FcmClientGetDefaultResponseFromJSON(json: any): ApiV1FcmClientGetDefaultResponse {
    return ApiV1FcmClientGetDefaultResponseFromJSONTyped(json, false);
}

export function ApiV1FcmClientGetDefaultResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1FcmClientGetDefaultResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ApiV1FcmClientGetDefaultResponseDataFromJSON(json['data']),
    };
}

export function ApiV1FcmClientGetDefaultResponseToJSON(value?: ApiV1FcmClientGetDefaultResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'message': value['message'],
        'data': ApiV1FcmClientGetDefaultResponseDataToJSON(value['data']),
    };
}

