/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ServerInfoGet200ResponseData
 */
export interface ApiV1ServerInfoGet200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof ApiV1ServerInfoGet200ResponseData
     */
    osVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ServerInfoGet200ResponseData
     */
    serverVersion?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1ServerInfoGet200ResponseData
     */
    privateApi?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ServerInfoGet200ResponseData
     */
    proxyService?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1ServerInfoGet200ResponseData
     */
    helperConnected?: boolean;
}

/**
 * Check if a given object implements the ApiV1ServerInfoGet200ResponseData interface.
 */
export function instanceOfApiV1ServerInfoGet200ResponseData(value: object): boolean {
    return true;
}

export function ApiV1ServerInfoGet200ResponseDataFromJSON(json: any): ApiV1ServerInfoGet200ResponseData {
    return ApiV1ServerInfoGet200ResponseDataFromJSONTyped(json, false);
}

export function ApiV1ServerInfoGet200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ServerInfoGet200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'osVersion': json['os_version'] == null ? undefined : json['os_version'],
        'serverVersion': json['server_version'] == null ? undefined : json['server_version'],
        'privateApi': json['private_api'] == null ? undefined : json['private_api'],
        'proxyService': json['proxy_service'] == null ? undefined : json['proxy_service'],
        'helperConnected': json['helper_connected'] == null ? undefined : json['helper_connected'],
    };
}

export function ApiV1ServerInfoGet200ResponseDataToJSON(value?: ApiV1ServerInfoGet200ResponseData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'os_version': value['osVersion'],
        'server_version': value['serverVersion'],
        'private_api': value['privateApi'],
        'proxy_service': value['proxyService'],
        'helper_connected': value['helperConnected'],
    };
}

