/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV1MessageQueryPostRequestWhereInner } from './ApiV1MessageQueryPostRequestWhereInner';
import {
    ApiV1MessageQueryPostRequestWhereInnerFromJSON,
    ApiV1MessageQueryPostRequestWhereInnerFromJSONTyped,
    ApiV1MessageQueryPostRequestWhereInnerToJSON,
} from './ApiV1MessageQueryPostRequestWhereInner';

/**
 * 
 * @export
 * @interface ApiV1MessageQueryPostRequest
 */
export interface ApiV1MessageQueryPostRequest {
    /**
     * 
     * @type {number}
     * @memberof ApiV1MessageQueryPostRequest
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV1MessageQueryPostRequest
     */
    offset?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1MessageQueryPostRequest
     */
    chatGuid?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiV1MessageQueryPostRequest
     */
    _with?: Array<string>;
    /**
     * 
     * @type {Array<ApiV1MessageQueryPostRequestWhereInner>}
     * @memberof ApiV1MessageQueryPostRequest
     */
    where?: Array<ApiV1MessageQueryPostRequestWhereInner>;
    /**
     * 
     * @type {string}
     * @memberof ApiV1MessageQueryPostRequest
     */
    sort?: string;
}

/**
 * Check if a given object implements the ApiV1MessageQueryPostRequest interface.
 */
export function instanceOfApiV1MessageQueryPostRequest(value: object): boolean {
    return true;
}

export function ApiV1MessageQueryPostRequestFromJSON(json: any): ApiV1MessageQueryPostRequest {
    return ApiV1MessageQueryPostRequestFromJSONTyped(json, false);
}

export function ApiV1MessageQueryPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1MessageQueryPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'chatGuid': json['chatGuid'] == null ? undefined : json['chatGuid'],
        '_with': json['with'] == null ? undefined : json['with'],
        'where': json['where'] == null ? undefined : ((json['where'] as Array<any>).map(ApiV1MessageQueryPostRequestWhereInnerFromJSON)),
        'sort': json['sort'] == null ? undefined : json['sort'],
    };
}

export function ApiV1MessageQueryPostRequestToJSON(value?: ApiV1MessageQueryPostRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'limit': value['limit'],
        'offset': value['offset'],
        'chatGuid': value['chatGuid'],
        'with': value['_with'],
        'where': value['where'] == null ? undefined : ((value['where'] as Array<any>).map(ApiV1MessageQueryPostRequestWhereInnerToJSON)),
        'sort': value['sort'],
    };
}

