/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV1ChatChatGUIDGet200ResponseData } from './ApiV1ChatChatGUIDGet200ResponseData';
import {
    ApiV1ChatChatGUIDGet200ResponseDataFromJSON,
    ApiV1ChatChatGUIDGet200ResponseDataFromJSONTyped,
    ApiV1ChatChatGUIDGet200ResponseDataToJSON,
} from './ApiV1ChatChatGUIDGet200ResponseData';

/**
 * 
 * @export
 * @interface ApiV1ChatChatGUIDGet200Response
 */
export interface ApiV1ChatChatGUIDGet200Response {
    /**
     * 
     * @type {number}
     * @memberof ApiV1ChatChatGUIDGet200Response
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ChatChatGUIDGet200Response
     */
    message?: string;
    /**
     * 
     * @type {ApiV1ChatChatGUIDGet200ResponseData}
     * @memberof ApiV1ChatChatGUIDGet200Response
     */
    data?: ApiV1ChatChatGUIDGet200ResponseData;
}

/**
 * Check if a given object implements the ApiV1ChatChatGUIDGet200Response interface.
 */
export function instanceOfApiV1ChatChatGUIDGet200Response(value: object): boolean {
    return true;
}

export function ApiV1ChatChatGUIDGet200ResponseFromJSON(json: any): ApiV1ChatChatGUIDGet200Response {
    return ApiV1ChatChatGUIDGet200ResponseFromJSONTyped(json, false);
}

export function ApiV1ChatChatGUIDGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ChatChatGUIDGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ApiV1ChatChatGUIDGet200ResponseDataFromJSON(json['data']),
    };
}

export function ApiV1ChatChatGUIDGet200ResponseToJSON(value?: ApiV1ChatChatGUIDGet200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'message': value['message'],
        'data': ApiV1ChatChatGUIDGet200ResponseDataToJSON(value['data']),
    };
}

