/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV1ChatChatGUIDGet200ResponseDataLastMessage } from './ApiV1ChatChatGUIDGet200ResponseDataLastMessage';
import {
    ApiV1ChatChatGUIDGet200ResponseDataLastMessageFromJSON,
    ApiV1ChatChatGUIDGet200ResponseDataLastMessageFromJSONTyped,
    ApiV1ChatChatGUIDGet200ResponseDataLastMessageToJSON,
} from './ApiV1ChatChatGUIDGet200ResponseDataLastMessage';
import type { ApiV1ChatChatGUIDGet200ResponseDataParticipantsInner } from './ApiV1ChatChatGUIDGet200ResponseDataParticipantsInner';
import {
    ApiV1ChatChatGUIDGet200ResponseDataParticipantsInnerFromJSON,
    ApiV1ChatChatGUIDGet200ResponseDataParticipantsInnerFromJSONTyped,
    ApiV1ChatChatGUIDGet200ResponseDataParticipantsInnerToJSON,
} from './ApiV1ChatChatGUIDGet200ResponseDataParticipantsInner';

/**
 * 
 * @export
 * @interface ApiV1ChatChatGUIDGet200ResponseData
 */
export interface ApiV1ChatChatGUIDGet200ResponseData {
    /**
     * 
     * @type {number}
     * @memberof ApiV1ChatChatGUIDGet200ResponseData
     */
    originalROWID?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ChatChatGUIDGet200ResponseData
     */
    guid?: string;
    /**
     * 
     * @type {Array<ApiV1ChatChatGUIDGet200ResponseDataParticipantsInner>}
     * @memberof ApiV1ChatChatGUIDGet200ResponseData
     */
    participants?: Array<ApiV1ChatChatGUIDGet200ResponseDataParticipantsInner>;
    /**
     * 
     * @type {Array<any>}
     * @memberof ApiV1ChatChatGUIDGet200ResponseData
     */
    messages?: Array<any>;
    /**
     * 
     * @type {number}
     * @memberof ApiV1ChatChatGUIDGet200ResponseData
     */
    style?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ChatChatGUIDGet200ResponseData
     */
    chatIdentifier?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1ChatChatGUIDGet200ResponseData
     */
    isArchived?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1ChatChatGUIDGet200ResponseData
     */
    isFiltered?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ChatChatGUIDGet200ResponseData
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ChatChatGUIDGet200ResponseData
     */
    groupId?: string;
    /**
     * 
     * @type {ApiV1ChatChatGUIDGet200ResponseDataLastMessage}
     * @memberof ApiV1ChatChatGUIDGet200ResponseData
     */
    lastMessage?: ApiV1ChatChatGUIDGet200ResponseDataLastMessage;
}

/**
 * Check if a given object implements the ApiV1ChatChatGUIDGet200ResponseData interface.
 */
export function instanceOfApiV1ChatChatGUIDGet200ResponseData(value: object): boolean {
    return true;
}

export function ApiV1ChatChatGUIDGet200ResponseDataFromJSON(json: any): ApiV1ChatChatGUIDGet200ResponseData {
    return ApiV1ChatChatGUIDGet200ResponseDataFromJSONTyped(json, false);
}

export function ApiV1ChatChatGUIDGet200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ChatChatGUIDGet200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'originalROWID': json['originalROWID'] == null ? undefined : json['originalROWID'],
        'guid': json['guid'] == null ? undefined : json['guid'],
        'participants': json['participants'] == null ? undefined : ((json['participants'] as Array<any>).map(ApiV1ChatChatGUIDGet200ResponseDataParticipantsInnerFromJSON)),
        'messages': json['messages'] == null ? undefined : json['messages'],
        'style': json['style'] == null ? undefined : json['style'],
        'chatIdentifier': json['chatIdentifier'] == null ? undefined : json['chatIdentifier'],
        'isArchived': json['isArchived'] == null ? undefined : json['isArchived'],
        'isFiltered': json['isFiltered'] == null ? undefined : json['isFiltered'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'groupId': json['groupId'] == null ? undefined : json['groupId'],
        'lastMessage': json['lastMessage'] == null ? undefined : ApiV1ChatChatGUIDGet200ResponseDataLastMessageFromJSON(json['lastMessage']),
    };
}

export function ApiV1ChatChatGUIDGet200ResponseDataToJSON(value?: ApiV1ChatChatGUIDGet200ResponseData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'originalROWID': value['originalROWID'],
        'guid': value['guid'],
        'participants': value['participants'] == null ? undefined : ((value['participants'] as Array<any>).map(ApiV1ChatChatGUIDGet200ResponseDataParticipantsInnerToJSON)),
        'messages': value['messages'],
        'style': value['style'],
        'chatIdentifier': value['chatIdentifier'],
        'isArchived': value['isArchived'],
        'isFiltered': value['isFiltered'],
        'displayName': value['displayName'],
        'groupId': value['groupId'],
        'lastMessage': ApiV1ChatChatGUIDGet200ResponseDataLastMessageToJSON(value['lastMessage']),
    };
}

