/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface ApiV1AttachmentCountGetRequest {
    password?: string;
}

export interface ApiV1AttachmentGUIDBlurhashGetRequest {
    password?: string;
    width?: number;
    height?: number;
    quality?: string;
}

export interface ApiV1AttachmentGUIDDownloadForceGetRequest {
    password?: string;
    width?: number;
    height?: number;
    quality?: string;
    original?: number;
}

export interface ApiV1AttachmentGUIDDownloadGetRequest {
    password?: string;
    width?: number;
    height?: number;
    quality?: string;
    original?: number;
}

export interface ApiV1AttachmentGUIDGetRequest {
    password?: string;
}

export interface ApiV1AttachmentGUIDLiveGetRequest {
    password?: string;
}

export interface ApiV1AttachmentUploadPostRequest {
    password?: string;
}

/**
 * AttachmentApi - interface
 * 
 * @export
 * @interface AttachmentApiInterface
 */
export interface AttachmentApiInterface {
    /**
     * Fetch the total number of attachments for your iMessage account (on the device)
     * @summary Get Attachment Count
     * @param {string} [password] Your BlueBubbles Server password
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AttachmentApiInterface
     */
    apiV1AttachmentCountGetRaw(requestParameters: ApiV1AttachmentCountGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Fetch the total number of attachments for your iMessage account (on the device)
     * Get Attachment Count
     */
    apiV1AttachmentCountGet(requestParameters: ApiV1AttachmentCountGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Generates a BlurHash string based on the given Attachment (by ID). You may optionally resize the image before the BlurHash is generated.  **Note**: Calculating a BlurHash is fairly intensive. Resizing the image to smaller size by specifying and/or height will reduce the time it takes to generate the hash string.
     * @summary Get Attachment Blurhash
     * @param {string} [password] Your BlueBubbles Server password
     * @param {number} [width] (Optional) A parameter specifying the value to resize the width to. This aspect ratio will be maintained if a height is not present.
     * @param {number} [height] (Optional) A parameter specifying the value to resize the height to. This aspect ratio will be maintained if a width is not present.
     * @param {string} [quality] (Optional) Change the quality of the image you are fetching. Must be one of: &#x60;good&#x60;, &#x60;better&#x60;, &#x60;best&#x60; (Default: &#x60;good&#x60;)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AttachmentApiInterface
     */
    apiV1AttachmentGUIDBlurhashGetRaw(requestParameters: ApiV1AttachmentGUIDBlurhashGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Generates a BlurHash string based on the given Attachment (by ID). You may optionally resize the image before the BlurHash is generated.  **Note**: Calculating a BlurHash is fairly intensive. Resizing the image to smaller size by specifying and/or height will reduce the time it takes to generate the hash string.
     * Get Attachment Blurhash
     */
    apiV1AttachmentGUIDBlurhashGet(requestParameters: ApiV1AttachmentGUIDBlurhashGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * **Private API Required**  Force download an iMessage Attachment by ID. You may optionally specify height/width parameters to resize the image.  This is different from the regular download endpoint as this will force the attachment to download if it\'s not already downloaded on the Mac. If an image isn\'t already downloaded on the Mac, and you use the regular download endpoint, you\'ll receive a 404 not found.
     * @summary Force Download Attachment
     * @param {string} [password] Your BlueBubbles Server password
     * @param {number} [width] (Optional) A parameter specifying the value to resize the width to. This aspect ratio will be maintained if a height is not present.
     * @param {number} [height] (Optional) A parameter specifying the value to resize the height to. This aspect ratio will be maintained if a width is not present..
     * @param {string} [quality] (Optional) Change the quality of the image you are fetching. Must be one of: &#x60;good&#x60;, &#x60;better&#x60;, &#x60;best&#x60;
     * @param {number} [original] (Optional) Download the original attachment (useful for auto-converted attachments like HEIC &amp; CAF)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AttachmentApiInterface
     */
    apiV1AttachmentGUIDDownloadForceGetRaw(requestParameters: ApiV1AttachmentGUIDDownloadForceGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * **Private API Required**  Force download an iMessage Attachment by ID. You may optionally specify height/width parameters to resize the image.  This is different from the regular download endpoint as this will force the attachment to download if it\'s not already downloaded on the Mac. If an image isn\'t already downloaded on the Mac, and you use the regular download endpoint, you\'ll receive a 404 not found.
     * Force Download Attachment
     */
    apiV1AttachmentGUIDDownloadForceGet(requestParameters: ApiV1AttachmentGUIDDownloadForceGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Download an iMessage Attachment by ID. You may optionally specify height/width parameters to resize the image.
     * @summary Download Attachment
     * @param {string} [password] Your BlueBubbles Server password
     * @param {number} [width] (Optional) A parameter specifying the value to resize the width to. This aspect ratio will be maintained if a height is not present.
     * @param {number} [height] (Optional) A parameter specifying the value to resize the height to. This aspect ratio will be maintained if a width is not present..
     * @param {string} [quality] (Optional) Change the quality of the image you are fetching. Must be one of: &#x60;good&#x60;, &#x60;better&#x60;, &#x60;best&#x60;
     * @param {number} [original] (Optional) Download the original attachment (useful for auto-converted attachments like HEIC &amp; CAF)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AttachmentApiInterface
     */
    apiV1AttachmentGUIDDownloadGetRaw(requestParameters: ApiV1AttachmentGUIDDownloadGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Download an iMessage Attachment by ID. You may optionally specify height/width parameters to resize the image.
     * Download Attachment
     */
    apiV1AttachmentGUIDDownloadGet(requestParameters: ApiV1AttachmentGUIDDownloadGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Fetch an Attachment\'s database information by ID
     * @summary Get Attachment by GUID
     * @param {string} [password] Your BlueBubbles Server password
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AttachmentApiInterface
     */
    apiV1AttachmentGUIDGetRaw(requestParameters: ApiV1AttachmentGUIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Fetch an Attachment\'s database information by ID
     * Get Attachment by GUID
     */
    apiV1AttachmentGUIDGet(requestParameters: ApiV1AttachmentGUIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Get\'s an attachment\'s \"live photo\" (if available).  If an attachment is not an image or does not have a live version, this endpoint will return an error indicating that a live photo does not exist for the attachment.
     * @summary Get Attachment Live Photo
     * @param {string} [password] Your BlueBubbles Server password
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AttachmentApiInterface
     */
    apiV1AttachmentGUIDLiveGetRaw(requestParameters: ApiV1AttachmentGUIDLiveGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Get\'s an attachment\'s \"live photo\" (if available).  If an attachment is not an image or does not have a live version, this endpoint will return an error indicating that a live photo does not exist for the attachment.
     * Get Attachment Live Photo
     */
    apiV1AttachmentGUIDLiveGet(requestParameters: ApiV1AttachmentGUIDLiveGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Upload an attachment to the server\'s iMessage attachments directory.  This is a pre-requisite and _must_ be done before sending an attachment as part of a _multipart_ message. This is **not** required when sending a normal attachment.  The response of this endpoint will be a unique identifier that you can use when sending a _multipart_ message.  #### Example Response  ``` json {     \"status\": 200,     \"message\": \"Success\",     \"data\": {         \"hash\": \"a04a23a0833b33db8a63ee0816948786\"     } }  ```
     * @summary Upload Attachment
     * @param {string} [password] Your BlueBubbles Server password
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AttachmentApiInterface
     */
    apiV1AttachmentUploadPostRaw(requestParameters: ApiV1AttachmentUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Upload an attachment to the server\'s iMessage attachments directory.  This is a pre-requisite and _must_ be done before sending an attachment as part of a _multipart_ message. This is **not** required when sending a normal attachment.  The response of this endpoint will be a unique identifier that you can use when sending a _multipart_ message.  #### Example Response  ``` json {     \"status\": 200,     \"message\": \"Success\",     \"data\": {         \"hash\": \"a04a23a0833b33db8a63ee0816948786\"     } }  ```
     * Upload Attachment
     */
    apiV1AttachmentUploadPost(requestParameters: ApiV1AttachmentUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class AttachmentApi extends runtime.BaseAPI implements AttachmentApiInterface {

    /**
     * Fetch the total number of attachments for your iMessage account (on the device)
     * Get Attachment Count
     */
    async apiV1AttachmentCountGetRaw(requestParameters: ApiV1AttachmentCountGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/attachment/count`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Fetch the total number of attachments for your iMessage account (on the device)
     * Get Attachment Count
     */
    async apiV1AttachmentCountGet(requestParameters: ApiV1AttachmentCountGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1AttachmentCountGetRaw(requestParameters, initOverrides);
    }

    /**
     * Generates a BlurHash string based on the given Attachment (by ID). You may optionally resize the image before the BlurHash is generated.  **Note**: Calculating a BlurHash is fairly intensive. Resizing the image to smaller size by specifying and/or height will reduce the time it takes to generate the hash string.
     * Get Attachment Blurhash
     */
    async apiV1AttachmentGUIDBlurhashGetRaw(requestParameters: ApiV1AttachmentGUIDBlurhashGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        if (requestParameters['width'] != null) {
            queryParameters['width'] = requestParameters['width'];
        }

        if (requestParameters['height'] != null) {
            queryParameters['height'] = requestParameters['height'];
        }

        if (requestParameters['quality'] != null) {
            queryParameters['quality'] = requestParameters['quality'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/attachment/<GUID>/blurhash`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Generates a BlurHash string based on the given Attachment (by ID). You may optionally resize the image before the BlurHash is generated.  **Note**: Calculating a BlurHash is fairly intensive. Resizing the image to smaller size by specifying and/or height will reduce the time it takes to generate the hash string.
     * Get Attachment Blurhash
     */
    async apiV1AttachmentGUIDBlurhashGet(requestParameters: ApiV1AttachmentGUIDBlurhashGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1AttachmentGUIDBlurhashGetRaw(requestParameters, initOverrides);
    }

    /**
     * **Private API Required**  Force download an iMessage Attachment by ID. You may optionally specify height/width parameters to resize the image.  This is different from the regular download endpoint as this will force the attachment to download if it\'s not already downloaded on the Mac. If an image isn\'t already downloaded on the Mac, and you use the regular download endpoint, you\'ll receive a 404 not found.
     * Force Download Attachment
     */
    async apiV1AttachmentGUIDDownloadForceGetRaw(requestParameters: ApiV1AttachmentGUIDDownloadForceGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        if (requestParameters['width'] != null) {
            queryParameters['width'] = requestParameters['width'];
        }

        if (requestParameters['height'] != null) {
            queryParameters['height'] = requestParameters['height'];
        }

        if (requestParameters['quality'] != null) {
            queryParameters['quality'] = requestParameters['quality'];
        }

        if (requestParameters['original'] != null) {
            queryParameters['original'] = requestParameters['original'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/attachment/<GUID>/download/force`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * **Private API Required**  Force download an iMessage Attachment by ID. You may optionally specify height/width parameters to resize the image.  This is different from the regular download endpoint as this will force the attachment to download if it\'s not already downloaded on the Mac. If an image isn\'t already downloaded on the Mac, and you use the regular download endpoint, you\'ll receive a 404 not found.
     * Force Download Attachment
     */
    async apiV1AttachmentGUIDDownloadForceGet(requestParameters: ApiV1AttachmentGUIDDownloadForceGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1AttachmentGUIDDownloadForceGetRaw(requestParameters, initOverrides);
    }

    /**
     * Download an iMessage Attachment by ID. You may optionally specify height/width parameters to resize the image.
     * Download Attachment
     */
    async apiV1AttachmentGUIDDownloadGetRaw(requestParameters: ApiV1AttachmentGUIDDownloadGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        if (requestParameters['width'] != null) {
            queryParameters['width'] = requestParameters['width'];
        }

        if (requestParameters['height'] != null) {
            queryParameters['height'] = requestParameters['height'];
        }

        if (requestParameters['quality'] != null) {
            queryParameters['quality'] = requestParameters['quality'];
        }

        if (requestParameters['original'] != null) {
            queryParameters['original'] = requestParameters['original'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/attachment/<GUID>/download`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Download an iMessage Attachment by ID. You may optionally specify height/width parameters to resize the image.
     * Download Attachment
     */
    async apiV1AttachmentGUIDDownloadGet(requestParameters: ApiV1AttachmentGUIDDownloadGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1AttachmentGUIDDownloadGetRaw(requestParameters, initOverrides);
    }

    /**
     * Fetch an Attachment\'s database information by ID
     * Get Attachment by GUID
     */
    async apiV1AttachmentGUIDGetRaw(requestParameters: ApiV1AttachmentGUIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/attachment/<GUID>`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Fetch an Attachment\'s database information by ID
     * Get Attachment by GUID
     */
    async apiV1AttachmentGUIDGet(requestParameters: ApiV1AttachmentGUIDGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1AttachmentGUIDGetRaw(requestParameters, initOverrides);
    }

    /**
     * Get\'s an attachment\'s \"live photo\" (if available).  If an attachment is not an image or does not have a live version, this endpoint will return an error indicating that a live photo does not exist for the attachment.
     * Get Attachment Live Photo
     */
    async apiV1AttachmentGUIDLiveGetRaw(requestParameters: ApiV1AttachmentGUIDLiveGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/attachment/<GUID>/live`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get\'s an attachment\'s \"live photo\" (if available).  If an attachment is not an image or does not have a live version, this endpoint will return an error indicating that a live photo does not exist for the attachment.
     * Get Attachment Live Photo
     */
    async apiV1AttachmentGUIDLiveGet(requestParameters: ApiV1AttachmentGUIDLiveGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1AttachmentGUIDLiveGetRaw(requestParameters, initOverrides);
    }

    /**
     * Upload an attachment to the server\'s iMessage attachments directory.  This is a pre-requisite and _must_ be done before sending an attachment as part of a _multipart_ message. This is **not** required when sending a normal attachment.  The response of this endpoint will be a unique identifier that you can use when sending a _multipart_ message.  #### Example Response  ``` json {     \"status\": 200,     \"message\": \"Success\",     \"data\": {         \"hash\": \"a04a23a0833b33db8a63ee0816948786\"     } }  ```
     * Upload Attachment
     */
    async apiV1AttachmentUploadPostRaw(requestParameters: ApiV1AttachmentUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/attachment/upload`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Upload an attachment to the server\'s iMessage attachments directory.  This is a pre-requisite and _must_ be done before sending an attachment as part of a _multipart_ message. This is **not** required when sending a normal attachment.  The response of this endpoint will be a unique identifier that you can use when sending a _multipart_ message.  #### Example Response  ``` json {     \"status\": 200,     \"message\": \"Success\",     \"data\": {         \"hash\": \"a04a23a0833b33db8a63ee0816948786\"     } }  ```
     * Upload Attachment
     */
    async apiV1AttachmentUploadPost(requestParameters: ApiV1AttachmentUploadPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1AttachmentUploadPostRaw(requestParameters, initOverrides);
    }

}
