/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiV1BackupThemeDeleteRequest,
  ApiV1BackupThemePostRequest,
} from '../models/index';
import {
    ApiV1BackupThemeDeleteRequestFromJSON,
    ApiV1BackupThemeDeleteRequestToJSON,
    ApiV1BackupThemePostRequestFromJSON,
    ApiV1BackupThemePostRequestToJSON,
} from '../models/index';

export interface ApiV1BackupSettingsDeleteRequest {
    password?: string;
    apiV1BackupThemeDeleteRequest?: ApiV1BackupThemeDeleteRequest;
}

export interface ApiV1BackupSettingsGetRequest {
    password?: string;
    name?: string;
}

export interface ApiV1BackupSettingsPostRequest {
    password?: string;
    apiV1BackupThemePostRequest?: ApiV1BackupThemePostRequest;
}

export interface ApiV1BackupThemeDeleteOperationRequest {
    password?: string;
    apiV1BackupThemeDeleteRequest?: ApiV1BackupThemeDeleteRequest;
}

export interface ApiV1BackupThemeGetRequest {
    password?: string;
    name?: string;
}

export interface ApiV1BackupThemePostOperationRequest {
    password?: string;
    apiV1BackupThemePostRequest?: ApiV1BackupThemePostRequest;
}

/**
 * BackupApi - interface
 * 
 * @export
 * @interface BackupApiInterface
 */
export interface BackupApiInterface {
    /**
     * Deletes a settings backup by name.  #### Request Body  ``` json {     // The name of your settings     \"name\": \"SettingsBackup - 2021/10/11\" }  ```
     * @summary Delete Settings
     * @param {string} [password] Your BlueBubbles Server password
     * @param {ApiV1BackupThemeDeleteRequest} [apiV1BackupThemeDeleteRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BackupApiInterface
     */
    apiV1BackupSettingsDeleteRaw(requestParameters: ApiV1BackupSettingsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Deletes a settings backup by name.  #### Request Body  ``` json {     // The name of your settings     \"name\": \"SettingsBackup - 2021/10/11\" }  ```
     * Delete Settings
     */
    apiV1BackupSettingsDelete(requestParameters: ApiV1BackupSettingsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Fetches settings saved to your BlueBubbles Server.
     * @summary Get Settings
     * @param {string} [password] Your BlueBubbles Server password
     * @param {string} [name] (Optional) Find a settings configuration by name. If no match is found, null is returned.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BackupApiInterface
     */
    apiV1BackupSettingsGetRaw(requestParameters: ApiV1BackupSettingsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Fetches settings saved to your BlueBubbles Server.
     * Get Settings
     */
    apiV1BackupSettingsGet(requestParameters: ApiV1BackupSettingsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Save a Settings configuration to your BlueBubbles Server App. This request has 2 required fields, `name` and `data`. Otherwise, the actual configuration data is up to the client. The only caveat is that clients that are pulling settings from the server need to be able to understand the format.  #### Request Body  ``` json {     // The name of your settings     \"name\": \"SettingsBackup - 2021/10/11\",     // The configuration data for your settings     \"data\": {} }  ```
     * @summary Save Settings
     * @param {string} [password] Your BlueBubbles Server password
     * @param {ApiV1BackupThemePostRequest} [apiV1BackupThemePostRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BackupApiInterface
     */
    apiV1BackupSettingsPostRaw(requestParameters: ApiV1BackupSettingsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Save a Settings configuration to your BlueBubbles Server App. This request has 2 required fields, `name` and `data`. Otherwise, the actual configuration data is up to the client. The only caveat is that clients that are pulling settings from the server need to be able to understand the format.  #### Request Body  ``` json {     // The name of your settings     \"name\": \"SettingsBackup - 2021/10/11\",     // The configuration data for your settings     \"data\": {} }  ```
     * Save Settings
     */
    apiV1BackupSettingsPost(requestParameters: ApiV1BackupSettingsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Deletes a theme backup by name.  #### Request Body  ``` json {     // The name of your theme     \"name\": \"SettingsBackup - 2021/10/11\" }  ```
     * @summary Delete Theme
     * @param {string} [password] Your BlueBubbles Server password
     * @param {ApiV1BackupThemeDeleteRequest} [apiV1BackupThemeDeleteRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BackupApiInterface
     */
    apiV1BackupThemeDeleteRaw(requestParameters: ApiV1BackupThemeDeleteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Deletes a theme backup by name.  #### Request Body  ``` json {     // The name of your theme     \"name\": \"SettingsBackup - 2021/10/11\" }  ```
     * Delete Theme
     */
    apiV1BackupThemeDelete(requestParameters: ApiV1BackupThemeDeleteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Fetches themes saved to your BlueBubbles Server.
     * @summary Get Themes
     * @param {string} [password] Your BlueBubbles Server password
     * @param {string} [name] (Optional) Find a theme by name. If no match is found, null is returned.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BackupApiInterface
     */
    apiV1BackupThemeGetRaw(requestParameters: ApiV1BackupThemeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Fetches themes saved to your BlueBubbles Server.
     * Get Themes
     */
    apiV1BackupThemeGet(requestParameters: ApiV1BackupThemeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Save a Theme to your BlueBubbles Server App. This request has 2 required fields, `name` and `data`. Otherwise, the actual configuration data is up to the client. The only caveat is that clients that are pulling themes from the server need to be able to understand the format.  #### Request Body  ```json {     // The name of your theme     \"name\": \"OLED Dark\",      // The configuration data for your theme     \"data\": {} } ```
     * @summary Save Theme
     * @param {string} [password] Your BlueBubbles Server password
     * @param {ApiV1BackupThemePostRequest} [apiV1BackupThemePostRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BackupApiInterface
     */
    apiV1BackupThemePostRaw(requestParameters: ApiV1BackupThemePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Save a Theme to your BlueBubbles Server App. This request has 2 required fields, `name` and `data`. Otherwise, the actual configuration data is up to the client. The only caveat is that clients that are pulling themes from the server need to be able to understand the format.  #### Request Body  ```json {     // The name of your theme     \"name\": \"OLED Dark\",      // The configuration data for your theme     \"data\": {} } ```
     * Save Theme
     */
    apiV1BackupThemePost(requestParameters: ApiV1BackupThemePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class BackupApi extends runtime.BaseAPI implements BackupApiInterface {

    /**
     * Deletes a settings backup by name.  #### Request Body  ``` json {     // The name of your settings     \"name\": \"SettingsBackup - 2021/10/11\" }  ```
     * Delete Settings
     */
    async apiV1BackupSettingsDeleteRaw(requestParameters: ApiV1BackupSettingsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/backup/settings`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: ApiV1BackupThemeDeleteRequestToJSON(requestParameters['apiV1BackupThemeDeleteRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a settings backup by name.  #### Request Body  ``` json {     // The name of your settings     \"name\": \"SettingsBackup - 2021/10/11\" }  ```
     * Delete Settings
     */
    async apiV1BackupSettingsDelete(requestParameters: ApiV1BackupSettingsDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1BackupSettingsDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Fetches settings saved to your BlueBubbles Server.
     * Get Settings
     */
    async apiV1BackupSettingsGetRaw(requestParameters: ApiV1BackupSettingsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/backup/settings`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Fetches settings saved to your BlueBubbles Server.
     * Get Settings
     */
    async apiV1BackupSettingsGet(requestParameters: ApiV1BackupSettingsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1BackupSettingsGetRaw(requestParameters, initOverrides);
    }

    /**
     * Save a Settings configuration to your BlueBubbles Server App. This request has 2 required fields, `name` and `data`. Otherwise, the actual configuration data is up to the client. The only caveat is that clients that are pulling settings from the server need to be able to understand the format.  #### Request Body  ``` json {     // The name of your settings     \"name\": \"SettingsBackup - 2021/10/11\",     // The configuration data for your settings     \"data\": {} }  ```
     * Save Settings
     */
    async apiV1BackupSettingsPostRaw(requestParameters: ApiV1BackupSettingsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/backup/settings`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiV1BackupThemePostRequestToJSON(requestParameters['apiV1BackupThemePostRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Save a Settings configuration to your BlueBubbles Server App. This request has 2 required fields, `name` and `data`. Otherwise, the actual configuration data is up to the client. The only caveat is that clients that are pulling settings from the server need to be able to understand the format.  #### Request Body  ``` json {     // The name of your settings     \"name\": \"SettingsBackup - 2021/10/11\",     // The configuration data for your settings     \"data\": {} }  ```
     * Save Settings
     */
    async apiV1BackupSettingsPost(requestParameters: ApiV1BackupSettingsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1BackupSettingsPostRaw(requestParameters, initOverrides);
    }

    /**
     * Deletes a theme backup by name.  #### Request Body  ``` json {     // The name of your theme     \"name\": \"SettingsBackup - 2021/10/11\" }  ```
     * Delete Theme
     */
    async apiV1BackupThemeDeleteRaw(requestParameters: ApiV1BackupThemeDeleteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/backup/theme`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: ApiV1BackupThemeDeleteRequestToJSON(requestParameters['apiV1BackupThemeDeleteRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a theme backup by name.  #### Request Body  ``` json {     // The name of your theme     \"name\": \"SettingsBackup - 2021/10/11\" }  ```
     * Delete Theme
     */
    async apiV1BackupThemeDelete(requestParameters: ApiV1BackupThemeDeleteOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1BackupThemeDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Fetches themes saved to your BlueBubbles Server.
     * Get Themes
     */
    async apiV1BackupThemeGetRaw(requestParameters: ApiV1BackupThemeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/backup/theme`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Fetches themes saved to your BlueBubbles Server.
     * Get Themes
     */
    async apiV1BackupThemeGet(requestParameters: ApiV1BackupThemeGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1BackupThemeGetRaw(requestParameters, initOverrides);
    }

    /**
     * Save a Theme to your BlueBubbles Server App. This request has 2 required fields, `name` and `data`. Otherwise, the actual configuration data is up to the client. The only caveat is that clients that are pulling themes from the server need to be able to understand the format.  #### Request Body  ```json {     // The name of your theme     \"name\": \"OLED Dark\",      // The configuration data for your theme     \"data\": {} } ```
     * Save Theme
     */
    async apiV1BackupThemePostRaw(requestParameters: ApiV1BackupThemePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/backup/theme`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiV1BackupThemePostRequestToJSON(requestParameters['apiV1BackupThemePostRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Save a Theme to your BlueBubbles Server App. This request has 2 required fields, `name` and `data`. Otherwise, the actual configuration data is up to the client. The only caveat is that clients that are pulling themes from the server need to be able to understand the format.  #### Request Body  ```json {     // The name of your theme     \"name\": \"OLED Dark\",      // The configuration data for your theme     \"data\": {} } ```
     * Save Theme
     */
    async apiV1BackupThemePost(requestParameters: ApiV1BackupThemePostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1BackupThemePostRaw(requestParameters, initOverrides);
    }

}
