/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiV1ChatChatGUIDGet200Response,
  ApiV1ChatChatGUIDGet404Response,
  ApiV1ChatChatGUIDMessageGet200Response,
  ApiV1ChatChatGUIDParticipantPostRequest,
  ApiV1ChatChatGUIDPutRequest,
  ApiV1ChatCountGet200Response,
  ApiV1ChatNewPostRequest,
  ApiV1ChatQueryPostRequest,
} from '../models/index';
import {
    ApiV1ChatChatGUIDGet200ResponseFromJSON,
    ApiV1ChatChatGUIDGet200ResponseToJSON,
    ApiV1ChatChatGUIDGet404ResponseFromJSON,
    ApiV1ChatChatGUIDGet404ResponseToJSON,
    ApiV1ChatChatGUIDMessageGet200ResponseFromJSON,
    ApiV1ChatChatGUIDMessageGet200ResponseToJSON,
    ApiV1ChatChatGUIDParticipantPostRequestFromJSON,
    ApiV1ChatChatGUIDParticipantPostRequestToJSON,
    ApiV1ChatChatGUIDPutRequestFromJSON,
    ApiV1ChatChatGUIDPutRequestToJSON,
    ApiV1ChatCountGet200ResponseFromJSON,
    ApiV1ChatCountGet200ResponseToJSON,
    ApiV1ChatNewPostRequestFromJSON,
    ApiV1ChatNewPostRequestToJSON,
    ApiV1ChatQueryPostRequestFromJSON,
    ApiV1ChatQueryPostRequestToJSON,
} from '../models/index';

export interface ApiV1ChatChatGUIDDeleteRequest {
    password?: string;
    body?: object;
}

export interface ApiV1ChatChatGUIDGetRequest {
    password?: string;
    _with?: string;
}

export interface ApiV1ChatChatGUIDIconDeleteRequest {
    password?: string;
}

export interface ApiV1ChatChatGUIDIconPostRequest {
    password?: string;
}

export interface ApiV1ChatChatGUIDLeavePostRequest {
    password?: string;
    body?: object;
}

export interface ApiV1ChatChatGUIDMessageGetRequest {
    password?: string;
    _with?: string;
    after?: string;
    before?: string;
    offset?: number;
    limit?: number;
    sort?: string;
}

export interface ApiV1ChatChatGUIDParticipantDeleteRequest {
    password?: string;
    apiV1ChatChatGUIDParticipantPostRequest?: ApiV1ChatChatGUIDParticipantPostRequest;
}

export interface ApiV1ChatChatGUIDParticipantPostOperationRequest {
    password?: string;
    apiV1ChatChatGUIDParticipantPostRequest?: ApiV1ChatChatGUIDParticipantPostRequest;
}

export interface ApiV1ChatChatGUIDPutOperationRequest {
    password?: string;
    apiV1ChatChatGUIDPutRequest?: ApiV1ChatChatGUIDPutRequest;
}

export interface ApiV1ChatChatGUIDReadPostRequest {
    password?: string;
    body?: object;
}

export interface ApiV1ChatChatGUIDShareContactPostRequest {
    password?: string;
    body?: object;
}

export interface ApiV1ChatChatGUIDShareContactStatusGetRequest {
    password?: string;
}

export interface ApiV1ChatChatGUIDTypingDeleteRequest {
    password?: string;
}

export interface ApiV1ChatChatGUIDTypingPostRequest {
    password?: string;
}

export interface ApiV1ChatChatGUIDUnreadPostRequest {
    password?: string;
    body?: object;
}

export interface ApiV1ChatCountGetRequest {
    password?: string;
}

export interface ApiV1ChatNewPostOperationRequest {
    password?: string;
    apiV1ChatNewPostRequest?: ApiV1ChatNewPostRequest;
}

export interface ApiV1ChatQueryPostOperationRequest {
    password?: string;
    apiV1ChatQueryPostRequest?: ApiV1ChatQueryPostRequest;
}

/**
 * ChatApi - interface
 * 
 * @export
 * @interface ChatApiInterface
 */
export interface ChatApiInterface {
    /**
     * Deletes a chat from the iMessage client on the macOS server. This will only apply to the macOS server\'s iMessage client, and no other Apple devices.  **Minimum BlueBubbles Server Version**: 1.3.0  **Requires:** Private API  #### Request Body  N/A
     * @summary Delete Chat
     * @param {string} [password] Your BlueBubbles Server password
     * @param {object} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChatApiInterface
     */
    apiV1ChatChatGUIDDeleteRaw(requestParameters: ApiV1ChatChatGUIDDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Deletes a chat from the iMessage client on the macOS server. This will only apply to the macOS server\'s iMessage client, and no other Apple devices.  **Minimum BlueBubbles Server Version**: 1.3.0  **Requires:** Private API  #### Request Body  N/A
     * Delete Chat
     */
    apiV1ChatChatGUIDDelete(requestParameters: ApiV1ChatChatGUIDDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Fetch a Chat\'s database information by ID
     * @summary Get Chat by GUID
     * @param {string} [password] Your BlueBubbles Server password
     * @param {string} [_with] (Optional) A comma-separated list of related items to fetch for this Chat. Must be one or more of: &#x60;lastmessage&#x60;, &#x60;participants&#x60;
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChatApiInterface
     */
    apiV1ChatChatGUIDGetRaw(requestParameters: ApiV1ChatChatGUIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ChatChatGUIDGet200Response>>;

    /**
     * Fetch a Chat\'s database information by ID
     * Get Chat by GUID
     */
    apiV1ChatChatGUIDGet(requestParameters: ApiV1ChatChatGUIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ChatChatGUIDGet200Response>;

    /**
     * Removes/Unsets a group chat\'s icon/photo.  **Requires:** Private API
     * @summary Remove Group Icon
     * @param {string} [password] Your BlueBubbles Server password
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChatApiInterface
     */
    apiV1ChatChatGUIDIconDeleteRaw(requestParameters: ApiV1ChatChatGUIDIconDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Removes/Unsets a group chat\'s icon/photo.  **Requires:** Private API
     * Remove Group Icon
     */
    apiV1ChatChatGUIDIconDelete(requestParameters: ApiV1ChatChatGUIDIconDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Set a group chat\'s icon/photo.  **Requires:** Private API
     * @summary Set Group Icon
     * @param {string} [password] Your BlueBubbles Server password
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChatApiInterface
     */
    apiV1ChatChatGUIDIconPostRaw(requestParameters: ApiV1ChatChatGUIDIconPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Set a group chat\'s icon/photo.  **Requires:** Private API
     * Set Group Icon
     */
    apiV1ChatChatGUIDIconPost(requestParameters: ApiV1ChatChatGUIDIconPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Allows you to leave a group chat that you are in.  An error will be thrown if the chat you are trying to leave is not a group chat.  **Requires:** Private API
     * @summary Leave Chat
     * @param {string} [password] Your BlueBubbles Server password
     * @param {object} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChatApiInterface
     */
    apiV1ChatChatGUIDLeavePostRaw(requestParameters: ApiV1ChatChatGUIDLeavePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Allows you to leave a group chat that you are in.  An error will be thrown if the chat you are trying to leave is not a group chat.  **Requires:** Private API
     * Leave Chat
     */
    apiV1ChatChatGUIDLeavePost(requestParameters: ApiV1ChatChatGUIDLeavePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Fetch messages associated with a specified chat
     * @summary Get Chat Messages
     * @param {string} [password] Your BlueBubbles Server password
     * @param {string} [_with] (Optional) What related information do you want returned with the messages? Must be one of: &#x60;attachment&#x60;, &#x60;handle&#x60;,  &#x60;sms&#x60;
     * @param {string} [after] (Optional) Fetches messages after a specified date, represented in seconds since EPOCH
     * @param {string} [before] (Optional) Fetches messages before a specified date, represented in seconds since EPOCH
     * @param {number} [offset] (Optional) A number representing the offset for the database query. This is useful for paging through data from the database to make database calls return as quick as possible. (Default: 0)
     * @param {number} [limit] (Optional) A number representing the limit for the database query. This is useful for paging through data from the database to make database calls return as quick as possible. (Default: 1000; Max: 1000)
     * @param {string} [sort] (Optional) How you want to sort the returned data by date. Must be one of: &#x60;ASC&#x60;, &#x60;DESC&#x60;
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChatApiInterface
     */
    apiV1ChatChatGUIDMessageGetRaw(requestParameters: ApiV1ChatChatGUIDMessageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ChatChatGUIDMessageGet200Response>>;

    /**
     * Fetch messages associated with a specified chat
     * Get Chat Messages
     */
    apiV1ChatChatGUIDMessageGet(requestParameters: ApiV1ChatChatGUIDMessageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ChatChatGUIDMessageGet200Response>;

    /**
     * Removes a participant from an existing chat  **Minimum BlueBubbles Server Version**: 0.3.0  **Requires:** Private API  #### Request Body  ```json {     // The participant address to remove     \"address\": \"\" } ```
     * @summary Remove Participant from Chat
     * @param {string} [password] Your BlueBubbles Server password
     * @param {ApiV1ChatChatGUIDParticipantPostRequest} [apiV1ChatChatGUIDParticipantPostRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChatApiInterface
     */
    apiV1ChatChatGUIDParticipantDeleteRaw(requestParameters: ApiV1ChatChatGUIDParticipantDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Removes a participant from an existing chat  **Minimum BlueBubbles Server Version**: 0.3.0  **Requires:** Private API  #### Request Body  ```json {     // The participant address to remove     \"address\": \"\" } ```
     * Remove Participant from Chat
     */
    apiV1ChatChatGUIDParticipantDelete(requestParameters: ApiV1ChatChatGUIDParticipantDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Adds a participant to an existing chat.  Include the country code (if possible). For instance, the country code for the United States is `+1`, so include a `1` at the start of the phone number from the US.  **Minimum BlueBubbles Server Version**: 0.3.0  **Requires:** Private API  #### Request Body  ``` json {     // The participant address to add     \"address\": \"\" }  ```
     * @summary Add Participant to Chat
     * @param {string} [password] Your BlueBubbles Server password
     * @param {ApiV1ChatChatGUIDParticipantPostRequest} [apiV1ChatChatGUIDParticipantPostRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChatApiInterface
     */
    apiV1ChatChatGUIDParticipantPostRaw(requestParameters: ApiV1ChatChatGUIDParticipantPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Adds a participant to an existing chat.  Include the country code (if possible). For instance, the country code for the United States is `+1`, so include a `1` at the start of the phone number from the US.  **Minimum BlueBubbles Server Version**: 0.3.0  **Requires:** Private API  #### Request Body  ``` json {     // The participant address to add     \"address\": \"\" }  ```
     * Add Participant to Chat
     */
    apiV1ChatChatGUIDParticipantPost(requestParameters: ApiV1ChatChatGUIDParticipantPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Updates an existing chat  **Minimum BlueBubbles Server Version**: 0.3.0  **Requires:** Private API  #### Request Body  ```json {     // (Optional) A new name for a group chat     \"displayName\": \"\" } ```
     * @summary Update a Chat
     * @param {string} [password] Your BlueBubbles Server password
     * @param {ApiV1ChatChatGUIDPutRequest} [apiV1ChatChatGUIDPutRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChatApiInterface
     */
    apiV1ChatChatGUIDPutRaw(requestParameters: ApiV1ChatChatGUIDPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Updates an existing chat  **Minimum BlueBubbles Server Version**: 0.3.0  **Requires:** Private API  #### Request Body  ```json {     // (Optional) A new name for a group chat     \"displayName\": \"\" } ```
     * Update a Chat
     */
    apiV1ChatChatGUIDPut(requestParameters: ApiV1ChatChatGUIDPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Marks a chat as read. This will also dispatch an event to other BlueBubbles clients indicating the chat should be marked read.  **Minimum BlueBubbles Server Version**: 1.1.0  **Requires:** Private API  #### Request Body  N/A
     * @summary Mark Chat as Read
     * @param {string} [password] Your BlueBubbles Server password
     * @param {object} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChatApiInterface
     */
    apiV1ChatChatGUIDReadPostRaw(requestParameters: ApiV1ChatChatGUIDReadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Marks a chat as read. This will also dispatch an event to other BlueBubbles clients indicating the chat should be marked read.  **Minimum BlueBubbles Server Version**: 1.1.0  **Requires:** Private API  #### Request Body  N/A
     * Mark Chat as Read
     */
    apiV1ChatChatGUIDReadPost(requestParameters: ApiV1ChatChatGUIDReadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Allows you to share your own iCloud Contact Card with another chat.
     * @summary Share Contact Info
     * @param {string} [password] Your BlueBubbles Server password
     * @param {object} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChatApiInterface
     */
    apiV1ChatChatGUIDShareContactPostRaw(requestParameters: ApiV1ChatChatGUIDShareContactPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Allows you to share your own iCloud Contact Card with another chat.
     * Share Contact Info
     */
    apiV1ChatChatGUIDShareContactPost(requestParameters: ApiV1ChatChatGUIDShareContactPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Fetch messages associated with a specified chat
     * @summary Get Contact Share Status
     * @param {string} [password] Your BlueBubbles Server password
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChatApiInterface
     */
    apiV1ChatChatGUIDShareContactStatusGetRaw(requestParameters: ApiV1ChatChatGUIDShareContactStatusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ChatChatGUIDMessageGet200Response>>;

    /**
     * Fetch messages associated with a specified chat
     * Get Contact Share Status
     */
    apiV1ChatChatGUIDShareContactStatusGet(requestParameters: ApiV1ChatChatGUIDShareContactStatusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ChatChatGUIDMessageGet200Response>;

    /**
     * Allows you to stop sending typing indicators to a chat  **Requires:** Private API  **Note:** Typing indicators will automatically stop when you send a message to the specified chat.
     * @summary Stop Send Typing Indicator
     * @param {string} [password] Your BlueBubbles Server password
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChatApiInterface
     */
    apiV1ChatChatGUIDTypingDeleteRaw(requestParameters: ApiV1ChatChatGUIDTypingDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Allows you to stop sending typing indicators to a chat  **Requires:** Private API  **Note:** Typing indicators will automatically stop when you send a message to the specified chat.
     * Stop Send Typing Indicator
     */
    apiV1ChatChatGUIDTypingDelete(requestParameters: ApiV1ChatChatGUIDTypingDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Allows you to start sending typing indicators to a chat  **Requires:** Private API  **Note:** Typing indicators will automatically stop when you send a message to the specified chat.
     * @summary Start Send Typing Indicator
     * @param {string} [password] Your BlueBubbles Server password
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChatApiInterface
     */
    apiV1ChatChatGUIDTypingPostRaw(requestParameters: ApiV1ChatChatGUIDTypingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Allows you to start sending typing indicators to a chat  **Requires:** Private API  **Note:** Typing indicators will automatically stop when you send a message to the specified chat.
     * Start Send Typing Indicator
     */
    apiV1ChatChatGUIDTypingPost(requestParameters: ApiV1ChatChatGUIDTypingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Marks a chat as unread. This will also dispatch an event to other BlueBubbles clients indicating the chat should be marked unread.  If you are not running macOS Ventura and send this API request, the event will still be dispatched to other BlueBubbles clients. However, it will not be marked as unread \"officially\" for other iOS devices.  **Minimum BlueBubbles Server Version**: 1.4.0  **Requires:**  - Private API - macOS Ventura       #### Request Body  N/A
     * @summary Mark Chat as Unread
     * @param {string} [password] Your BlueBubbles Server password
     * @param {object} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChatApiInterface
     */
    apiV1ChatChatGUIDUnreadPostRaw(requestParameters: ApiV1ChatChatGUIDUnreadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Marks a chat as unread. This will also dispatch an event to other BlueBubbles clients indicating the chat should be marked unread.  If you are not running macOS Ventura and send this API request, the event will still be dispatched to other BlueBubbles clients. However, it will not be marked as unread \"officially\" for other iOS devices.  **Minimum BlueBubbles Server Version**: 1.4.0  **Requires:**  - Private API - macOS Ventura       #### Request Body  N/A
     * Mark Chat as Unread
     */
    apiV1ChatChatGUIDUnreadPost(requestParameters: ApiV1ChatChatGUIDUnreadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Get the total number of chats for your iMessage account (on the device)
     * @summary Get Chat Count
     * @param {string} [password] Your BlueBubbles Server password
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChatApiInterface
     */
    apiV1ChatCountGetRaw(requestParameters: ApiV1ChatCountGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ChatCountGet200Response>>;

    /**
     * Get the total number of chats for your iMessage account (on the device)
     * Get Chat Count
     */
    apiV1ChatCountGet(requestParameters: ApiV1ChatCountGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ChatCountGet200Response>;

    /**
     * Create a new iMessage chat  **Minimum BlueBubbles Server Version**: 0.3.0  **Requires:** Private API  #### Request Body  ```json {     // A list of participants for the chat     \"addresses\": [],     // (Optional) A message to send in the new chat     \"message\": \"An optional message to send\" } ```
     * @summary Create New Chat
     * @param {string} [password] Your BlueBubbles Server password
     * @param {ApiV1ChatNewPostRequest} [apiV1ChatNewPostRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChatApiInterface
     */
    apiV1ChatNewPostRaw(requestParameters: ApiV1ChatNewPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Create a new iMessage chat  **Minimum BlueBubbles Server Version**: 0.3.0  **Requires:** Private API  #### Request Body  ```json {     // A list of participants for the chat     \"addresses\": [],     // (Optional) A message to send in the new chat     \"message\": \"An optional message to send\" } ```
     * Create New Chat
     */
    apiV1ChatNewPost(requestParameters: ApiV1ChatNewPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Query for Chats from the database  #### Request Body  ``` json {     // (Optional) A number representing the offset for the database query.     // This is useful for paging through data from the database to make database calls return as quick as possible.     // (Default: 0)     \"limit\": 1000,     //( Optional) A number representing the offset for the database query.     // This is useful for paging through data from the database to make database calls return as quick as possible.     // (Default: 0)     \"offset\": 0,     // (Optional) What related information do you want returned with the messages?     // Must be one of: `participants`, `lastmessage`, `sms`, `archived`, `message.attributed-body`, `message.message-info-summary`, `message.payload-data`     \"with\": [         \"lastMessage\",         \"participants\",         \"sms\",         \"archived\"     ],     // (Optional) How the returned data should be sorted.     // In order to sort, `lastmessage` must be included in the `with` parameter.     // Must be: `lastmessage`     \"sort\": \"lastmessage\" }  ```
     * @summary Query Chats
     * @param {string} [password] Your BlueBubbles Server password
     * @param {ApiV1ChatQueryPostRequest} [apiV1ChatQueryPostRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChatApiInterface
     */
    apiV1ChatQueryPostRaw(requestParameters: ApiV1ChatQueryPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Query for Chats from the database  #### Request Body  ``` json {     // (Optional) A number representing the offset for the database query.     // This is useful for paging through data from the database to make database calls return as quick as possible.     // (Default: 0)     \"limit\": 1000,     //( Optional) A number representing the offset for the database query.     // This is useful for paging through data from the database to make database calls return as quick as possible.     // (Default: 0)     \"offset\": 0,     // (Optional) What related information do you want returned with the messages?     // Must be one of: `participants`, `lastmessage`, `sms`, `archived`, `message.attributed-body`, `message.message-info-summary`, `message.payload-data`     \"with\": [         \"lastMessage\",         \"participants\",         \"sms\",         \"archived\"     ],     // (Optional) How the returned data should be sorted.     // In order to sort, `lastmessage` must be included in the `with` parameter.     // Must be: `lastmessage`     \"sort\": \"lastmessage\" }  ```
     * Query Chats
     */
    apiV1ChatQueryPost(requestParameters: ApiV1ChatQueryPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class ChatApi extends runtime.BaseAPI implements ChatApiInterface {

    /**
     * Deletes a chat from the iMessage client on the macOS server. This will only apply to the macOS server\'s iMessage client, and no other Apple devices.  **Minimum BlueBubbles Server Version**: 1.3.0  **Requires:** Private API  #### Request Body  N/A
     * Delete Chat
     */
    async apiV1ChatChatGUIDDeleteRaw(requestParameters: ApiV1ChatChatGUIDDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/chat/<Chat GUID>`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a chat from the iMessage client on the macOS server. This will only apply to the macOS server\'s iMessage client, and no other Apple devices.  **Minimum BlueBubbles Server Version**: 1.3.0  **Requires:** Private API  #### Request Body  N/A
     * Delete Chat
     */
    async apiV1ChatChatGUIDDelete(requestParameters: ApiV1ChatChatGUIDDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1ChatChatGUIDDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Fetch a Chat\'s database information by ID
     * Get Chat by GUID
     */
    async apiV1ChatChatGUIDGetRaw(requestParameters: ApiV1ChatChatGUIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ChatChatGUIDGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        if (requestParameters['_with'] != null) {
            queryParameters['with'] = requestParameters['_with'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/chat/<Chat GUID>`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1ChatChatGUIDGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Fetch a Chat\'s database information by ID
     * Get Chat by GUID
     */
    async apiV1ChatChatGUIDGet(requestParameters: ApiV1ChatChatGUIDGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ChatChatGUIDGet200Response> {
        const response = await this.apiV1ChatChatGUIDGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Removes/Unsets a group chat\'s icon/photo.  **Requires:** Private API
     * Remove Group Icon
     */
    async apiV1ChatChatGUIDIconDeleteRaw(requestParameters: ApiV1ChatChatGUIDIconDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/chat/<Chat GUID>/icon`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes/Unsets a group chat\'s icon/photo.  **Requires:** Private API
     * Remove Group Icon
     */
    async apiV1ChatChatGUIDIconDelete(requestParameters: ApiV1ChatChatGUIDIconDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1ChatChatGUIDIconDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Set a group chat\'s icon/photo.  **Requires:** Private API
     * Set Group Icon
     */
    async apiV1ChatChatGUIDIconPostRaw(requestParameters: ApiV1ChatChatGUIDIconPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/chat/<Chat GUID>/icon`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Set a group chat\'s icon/photo.  **Requires:** Private API
     * Set Group Icon
     */
    async apiV1ChatChatGUIDIconPost(requestParameters: ApiV1ChatChatGUIDIconPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1ChatChatGUIDIconPostRaw(requestParameters, initOverrides);
    }

    /**
     * Allows you to leave a group chat that you are in.  An error will be thrown if the chat you are trying to leave is not a group chat.  **Requires:** Private API
     * Leave Chat
     */
    async apiV1ChatChatGUIDLeavePostRaw(requestParameters: ApiV1ChatChatGUIDLeavePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/chat/<Chat GUID>/leave`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Allows you to leave a group chat that you are in.  An error will be thrown if the chat you are trying to leave is not a group chat.  **Requires:** Private API
     * Leave Chat
     */
    async apiV1ChatChatGUIDLeavePost(requestParameters: ApiV1ChatChatGUIDLeavePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1ChatChatGUIDLeavePostRaw(requestParameters, initOverrides);
    }

    /**
     * Fetch messages associated with a specified chat
     * Get Chat Messages
     */
    async apiV1ChatChatGUIDMessageGetRaw(requestParameters: ApiV1ChatChatGUIDMessageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ChatChatGUIDMessageGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        if (requestParameters['_with'] != null) {
            queryParameters['with'] = requestParameters['_with'];
        }

        if (requestParameters['after'] != null) {
            queryParameters['after'] = requestParameters['after'];
        }

        if (requestParameters['before'] != null) {
            queryParameters['before'] = requestParameters['before'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/chat/<Chat GUID>/message`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1ChatChatGUIDMessageGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Fetch messages associated with a specified chat
     * Get Chat Messages
     */
    async apiV1ChatChatGUIDMessageGet(requestParameters: ApiV1ChatChatGUIDMessageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ChatChatGUIDMessageGet200Response> {
        const response = await this.apiV1ChatChatGUIDMessageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Removes a participant from an existing chat  **Minimum BlueBubbles Server Version**: 0.3.0  **Requires:** Private API  #### Request Body  ```json {     // The participant address to remove     \"address\": \"\" } ```
     * Remove Participant from Chat
     */
    async apiV1ChatChatGUIDParticipantDeleteRaw(requestParameters: ApiV1ChatChatGUIDParticipantDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/chat/<Chat GUID>/participant`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: ApiV1ChatChatGUIDParticipantPostRequestToJSON(requestParameters['apiV1ChatChatGUIDParticipantPostRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes a participant from an existing chat  **Minimum BlueBubbles Server Version**: 0.3.0  **Requires:** Private API  #### Request Body  ```json {     // The participant address to remove     \"address\": \"\" } ```
     * Remove Participant from Chat
     */
    async apiV1ChatChatGUIDParticipantDelete(requestParameters: ApiV1ChatChatGUIDParticipantDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1ChatChatGUIDParticipantDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Adds a participant to an existing chat.  Include the country code (if possible). For instance, the country code for the United States is `+1`, so include a `1` at the start of the phone number from the US.  **Minimum BlueBubbles Server Version**: 0.3.0  **Requires:** Private API  #### Request Body  ``` json {     // The participant address to add     \"address\": \"\" }  ```
     * Add Participant to Chat
     */
    async apiV1ChatChatGUIDParticipantPostRaw(requestParameters: ApiV1ChatChatGUIDParticipantPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/chat/<Chat GUID>/participant`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiV1ChatChatGUIDParticipantPostRequestToJSON(requestParameters['apiV1ChatChatGUIDParticipantPostRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Adds a participant to an existing chat.  Include the country code (if possible). For instance, the country code for the United States is `+1`, so include a `1` at the start of the phone number from the US.  **Minimum BlueBubbles Server Version**: 0.3.0  **Requires:** Private API  #### Request Body  ``` json {     // The participant address to add     \"address\": \"\" }  ```
     * Add Participant to Chat
     */
    async apiV1ChatChatGUIDParticipantPost(requestParameters: ApiV1ChatChatGUIDParticipantPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1ChatChatGUIDParticipantPostRaw(requestParameters, initOverrides);
    }

    /**
     * Updates an existing chat  **Minimum BlueBubbles Server Version**: 0.3.0  **Requires:** Private API  #### Request Body  ```json {     // (Optional) A new name for a group chat     \"displayName\": \"\" } ```
     * Update a Chat
     */
    async apiV1ChatChatGUIDPutRaw(requestParameters: ApiV1ChatChatGUIDPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/chat/<Chat GUID>`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ApiV1ChatChatGUIDPutRequestToJSON(requestParameters['apiV1ChatChatGUIDPutRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Updates an existing chat  **Minimum BlueBubbles Server Version**: 0.3.0  **Requires:** Private API  #### Request Body  ```json {     // (Optional) A new name for a group chat     \"displayName\": \"\" } ```
     * Update a Chat
     */
    async apiV1ChatChatGUIDPut(requestParameters: ApiV1ChatChatGUIDPutOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1ChatChatGUIDPutRaw(requestParameters, initOverrides);
    }

    /**
     * Marks a chat as read. This will also dispatch an event to other BlueBubbles clients indicating the chat should be marked read.  **Minimum BlueBubbles Server Version**: 1.1.0  **Requires:** Private API  #### Request Body  N/A
     * Mark Chat as Read
     */
    async apiV1ChatChatGUIDReadPostRaw(requestParameters: ApiV1ChatChatGUIDReadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/chat/<Chat GUID>/read`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Marks a chat as read. This will also dispatch an event to other BlueBubbles clients indicating the chat should be marked read.  **Minimum BlueBubbles Server Version**: 1.1.0  **Requires:** Private API  #### Request Body  N/A
     * Mark Chat as Read
     */
    async apiV1ChatChatGUIDReadPost(requestParameters: ApiV1ChatChatGUIDReadPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1ChatChatGUIDReadPostRaw(requestParameters, initOverrides);
    }

    /**
     * Allows you to share your own iCloud Contact Card with another chat.
     * Share Contact Info
     */
    async apiV1ChatChatGUIDShareContactPostRaw(requestParameters: ApiV1ChatChatGUIDShareContactPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/chat/<Chat GUID>/share/contact`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Allows you to share your own iCloud Contact Card with another chat.
     * Share Contact Info
     */
    async apiV1ChatChatGUIDShareContactPost(requestParameters: ApiV1ChatChatGUIDShareContactPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1ChatChatGUIDShareContactPostRaw(requestParameters, initOverrides);
    }

    /**
     * Fetch messages associated with a specified chat
     * Get Contact Share Status
     */
    async apiV1ChatChatGUIDShareContactStatusGetRaw(requestParameters: ApiV1ChatChatGUIDShareContactStatusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ChatChatGUIDMessageGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/chat/<Chat GUID>/share/contact/status`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1ChatChatGUIDMessageGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Fetch messages associated with a specified chat
     * Get Contact Share Status
     */
    async apiV1ChatChatGUIDShareContactStatusGet(requestParameters: ApiV1ChatChatGUIDShareContactStatusGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ChatChatGUIDMessageGet200Response> {
        const response = await this.apiV1ChatChatGUIDShareContactStatusGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Allows you to stop sending typing indicators to a chat  **Requires:** Private API  **Note:** Typing indicators will automatically stop when you send a message to the specified chat.
     * Stop Send Typing Indicator
     */
    async apiV1ChatChatGUIDTypingDeleteRaw(requestParameters: ApiV1ChatChatGUIDTypingDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/chat/<Chat GUID>/typing`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Allows you to stop sending typing indicators to a chat  **Requires:** Private API  **Note:** Typing indicators will automatically stop when you send a message to the specified chat.
     * Stop Send Typing Indicator
     */
    async apiV1ChatChatGUIDTypingDelete(requestParameters: ApiV1ChatChatGUIDTypingDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1ChatChatGUIDTypingDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Allows you to start sending typing indicators to a chat  **Requires:** Private API  **Note:** Typing indicators will automatically stop when you send a message to the specified chat.
     * Start Send Typing Indicator
     */
    async apiV1ChatChatGUIDTypingPostRaw(requestParameters: ApiV1ChatChatGUIDTypingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/chat/<Chat GUID>/typing`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Allows you to start sending typing indicators to a chat  **Requires:** Private API  **Note:** Typing indicators will automatically stop when you send a message to the specified chat.
     * Start Send Typing Indicator
     */
    async apiV1ChatChatGUIDTypingPost(requestParameters: ApiV1ChatChatGUIDTypingPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1ChatChatGUIDTypingPostRaw(requestParameters, initOverrides);
    }

    /**
     * Marks a chat as unread. This will also dispatch an event to other BlueBubbles clients indicating the chat should be marked unread.  If you are not running macOS Ventura and send this API request, the event will still be dispatched to other BlueBubbles clients. However, it will not be marked as unread \"officially\" for other iOS devices.  **Minimum BlueBubbles Server Version**: 1.4.0  **Requires:**  - Private API - macOS Ventura       #### Request Body  N/A
     * Mark Chat as Unread
     */
    async apiV1ChatChatGUIDUnreadPostRaw(requestParameters: ApiV1ChatChatGUIDUnreadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/chat/<Chat GUID>/unread`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Marks a chat as unread. This will also dispatch an event to other BlueBubbles clients indicating the chat should be marked unread.  If you are not running macOS Ventura and send this API request, the event will still be dispatched to other BlueBubbles clients. However, it will not be marked as unread \"officially\" for other iOS devices.  **Minimum BlueBubbles Server Version**: 1.4.0  **Requires:**  - Private API - macOS Ventura       #### Request Body  N/A
     * Mark Chat as Unread
     */
    async apiV1ChatChatGUIDUnreadPost(requestParameters: ApiV1ChatChatGUIDUnreadPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1ChatChatGUIDUnreadPostRaw(requestParameters, initOverrides);
    }

    /**
     * Get the total number of chats for your iMessage account (on the device)
     * Get Chat Count
     */
    async apiV1ChatCountGetRaw(requestParameters: ApiV1ChatCountGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ChatCountGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/chat/count`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1ChatCountGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get the total number of chats for your iMessage account (on the device)
     * Get Chat Count
     */
    async apiV1ChatCountGet(requestParameters: ApiV1ChatCountGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ChatCountGet200Response> {
        const response = await this.apiV1ChatCountGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new iMessage chat  **Minimum BlueBubbles Server Version**: 0.3.0  **Requires:** Private API  #### Request Body  ```json {     // A list of participants for the chat     \"addresses\": [],     // (Optional) A message to send in the new chat     \"message\": \"An optional message to send\" } ```
     * Create New Chat
     */
    async apiV1ChatNewPostRaw(requestParameters: ApiV1ChatNewPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/chat/new`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiV1ChatNewPostRequestToJSON(requestParameters['apiV1ChatNewPostRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a new iMessage chat  **Minimum BlueBubbles Server Version**: 0.3.0  **Requires:** Private API  #### Request Body  ```json {     // A list of participants for the chat     \"addresses\": [],     // (Optional) A message to send in the new chat     \"message\": \"An optional message to send\" } ```
     * Create New Chat
     */
    async apiV1ChatNewPost(requestParameters: ApiV1ChatNewPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1ChatNewPostRaw(requestParameters, initOverrides);
    }

    /**
     * Query for Chats from the database  #### Request Body  ``` json {     // (Optional) A number representing the offset for the database query.     // This is useful for paging through data from the database to make database calls return as quick as possible.     // (Default: 0)     \"limit\": 1000,     //( Optional) A number representing the offset for the database query.     // This is useful for paging through data from the database to make database calls return as quick as possible.     // (Default: 0)     \"offset\": 0,     // (Optional) What related information do you want returned with the messages?     // Must be one of: `participants`, `lastmessage`, `sms`, `archived`, `message.attributed-body`, `message.message-info-summary`, `message.payload-data`     \"with\": [         \"lastMessage\",         \"participants\",         \"sms\",         \"archived\"     ],     // (Optional) How the returned data should be sorted.     // In order to sort, `lastmessage` must be included in the `with` parameter.     // Must be: `lastmessage`     \"sort\": \"lastmessage\" }  ```
     * Query Chats
     */
    async apiV1ChatQueryPostRaw(requestParameters: ApiV1ChatQueryPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/chat/query`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiV1ChatQueryPostRequestToJSON(requestParameters['apiV1ChatQueryPostRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Query for Chats from the database  #### Request Body  ``` json {     // (Optional) A number representing the offset for the database query.     // This is useful for paging through data from the database to make database calls return as quick as possible.     // (Default: 0)     \"limit\": 1000,     //( Optional) A number representing the offset for the database query.     // This is useful for paging through data from the database to make database calls return as quick as possible.     // (Default: 0)     \"offset\": 0,     // (Optional) What related information do you want returned with the messages?     // Must be one of: `participants`, `lastmessage`, `sms`, `archived`, `message.attributed-body`, `message.message-info-summary`, `message.payload-data`     \"with\": [         \"lastMessage\",         \"participants\",         \"sms\",         \"archived\"     ],     // (Optional) How the returned data should be sorted.     // In order to sort, `lastmessage` must be included in the `with` parameter.     // Must be: `lastmessage`     \"sort\": \"lastmessage\" }  ```
     * Query Chats
     */
    async apiV1ChatQueryPost(requestParameters: ApiV1ChatQueryPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1ChatQueryPostRaw(requestParameters, initOverrides);
    }

}
