/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiV1ContactQueryPostRequest,
} from '../models/index';
import {
    ApiV1ContactQueryPostRequestFromJSON,
    ApiV1ContactQueryPostRequestToJSON,
} from '../models/index';

export interface ApiV1ContactGetRequest {
    password?: string;
}

export interface ApiV1ContactQueryPostOperationRequest {
    password?: string;
    apiV1ContactQueryPostRequest?: ApiV1ContactQueryPostRequest;
}

/**
 * ContactApi - interface
 * 
 * @export
 * @interface ContactApiInterface
 */
export interface ContactApiInterface {
    /**
     * Fetch contacts from your macOS device
     * @summary Get Contacts
     * @param {string} [password] Your BlueBubbles Server password
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactApiInterface
     */
    apiV1ContactGetRaw(requestParameters: ApiV1ContactGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Fetch contacts from your macOS device
     * Get Contacts
     */
    apiV1ContactGet(requestParameters: ApiV1ContactGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Query your contacts from your macOS device.  #### Request Body  ```json {     // (Optional) A list of one or more addresses to return data for     \"addresses\": [] } ```
     * @summary Query Contacts
     * @param {string} [password] Your BlueBubbles Server password
     * @param {ApiV1ContactQueryPostRequest} [apiV1ContactQueryPostRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactApiInterface
     */
    apiV1ContactQueryPostRaw(requestParameters: ApiV1ContactQueryPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Query your contacts from your macOS device.  #### Request Body  ```json {     // (Optional) A list of one or more addresses to return data for     \"addresses\": [] } ```
     * Query Contacts
     */
    apiV1ContactQueryPost(requestParameters: ApiV1ContactQueryPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class ContactApi extends runtime.BaseAPI implements ContactApiInterface {

    /**
     * Fetch contacts from your macOS device
     * Get Contacts
     */
    async apiV1ContactGetRaw(requestParameters: ApiV1ContactGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/contact`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Fetch contacts from your macOS device
     * Get Contacts
     */
    async apiV1ContactGet(requestParameters: ApiV1ContactGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1ContactGetRaw(requestParameters, initOverrides);
    }

    /**
     * Query your contacts from your macOS device.  #### Request Body  ```json {     // (Optional) A list of one or more addresses to return data for     \"addresses\": [] } ```
     * Query Contacts
     */
    async apiV1ContactQueryPostRaw(requestParameters: ApiV1ContactQueryPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/contact/query`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiV1ContactQueryPostRequestToJSON(requestParameters['apiV1ContactQueryPostRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Query your contacts from your macOS device.  #### Request Body  ```json {     // (Optional) A list of one or more addresses to return data for     \"addresses\": [] } ```
     * Query Contacts
     */
    async apiV1ContactQueryPost(requestParameters: ApiV1ContactQueryPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1ContactQueryPostRaw(requestParameters, initOverrides);
    }

}
