/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiV1FcmClientGetDefaultResponse,
  ApiV1FcmDevicePostRequest,
} from '../models/index';
import {
    ApiV1FcmClientGetDefaultResponseFromJSON,
    ApiV1FcmClientGetDefaultResponseToJSON,
    ApiV1FcmDevicePostRequestFromJSON,
    ApiV1FcmDevicePostRequestToJSON,
} from '../models/index';

export interface ApiV1FcmClientGetRequest {
    password?: string;
    apiV1FcmDevicePostRequest?: ApiV1FcmDevicePostRequest;
}

export interface ApiV1FcmDevicePostOperationRequest {
    password?: string;
    apiV1FcmDevicePostRequest?: ApiV1FcmDevicePostRequest;
}

/**
 * FCMApi - interface
 * 
 * @export
 * @interface FCMApiInterface
 */
export interface FCMApiInterface {
    /**
     * Fetches your Server\'s FCM Client Configuration so you can register your device with Google Firebase.
     * @summary Get FCM Client Config
     * @param {string} [password] Your BlueBubbles Server password
     * @param {ApiV1FcmDevicePostRequest} [apiV1FcmDevicePostRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FCMApiInterface
     */
    apiV1FcmClientGetRaw(requestParameters: ApiV1FcmClientGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1FcmClientGetDefaultResponse>>;

    /**
     * Fetches your Server\'s FCM Client Configuration so you can register your device with Google Firebase.
     * Get FCM Client Config
     */
    apiV1FcmClientGet(requestParameters: ApiV1FcmClientGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1FcmClientGetDefaultResponse>;

    /**
     * Registers a device for Google FCM Notifications  #### Request Body  ```json {     // A name for the device you are registering     \"name\": \"pixel5a\",     // A unique identifier string that Google FCM will use to send notifications to your device.     // This is typically generated when you authenticate with Google FCM.     \"identifier\": \"\" } ```
     * @summary Register Device
     * @param {string} [password] Your BlueBubbles Server password
     * @param {ApiV1FcmDevicePostRequest} [apiV1FcmDevicePostRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FCMApiInterface
     */
    apiV1FcmDevicePostRaw(requestParameters: ApiV1FcmDevicePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Registers a device for Google FCM Notifications  #### Request Body  ```json {     // A name for the device you are registering     \"name\": \"pixel5a\",     // A unique identifier string that Google FCM will use to send notifications to your device.     // This is typically generated when you authenticate with Google FCM.     \"identifier\": \"\" } ```
     * Register Device
     */
    apiV1FcmDevicePost(requestParameters: ApiV1FcmDevicePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class FCMApi extends runtime.BaseAPI implements FCMApiInterface {

    /**
     * Fetches your Server\'s FCM Client Configuration so you can register your device with Google Firebase.
     * Get FCM Client Config
     */
    async apiV1FcmClientGetRaw(requestParameters: ApiV1FcmClientGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1FcmClientGetDefaultResponse>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/fcm/client`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: ApiV1FcmDevicePostRequestToJSON(requestParameters['apiV1FcmDevicePostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1FcmClientGetDefaultResponseFromJSON(jsonValue));
    }

    /**
     * Fetches your Server\'s FCM Client Configuration so you can register your device with Google Firebase.
     * Get FCM Client Config
     */
    async apiV1FcmClientGet(requestParameters: ApiV1FcmClientGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1FcmClientGetDefaultResponse> {
        const response = await this.apiV1FcmClientGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Registers a device for Google FCM Notifications  #### Request Body  ```json {     // A name for the device you are registering     \"name\": \"pixel5a\",     // A unique identifier string that Google FCM will use to send notifications to your device.     // This is typically generated when you authenticate with Google FCM.     \"identifier\": \"\" } ```
     * Register Device
     */
    async apiV1FcmDevicePostRaw(requestParameters: ApiV1FcmDevicePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/fcm/device`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiV1FcmDevicePostRequestToJSON(requestParameters['apiV1FcmDevicePostRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Registers a device for Google FCM Notifications  #### Request Body  ```json {     // A name for the device you are registering     \"name\": \"pixel5a\",     // A unique identifier string that Google FCM will use to send notifications to your device.     // This is typically generated when you authenticate with Google FCM.     \"identifier\": \"\" } ```
     * Register Device
     */
    async apiV1FcmDevicePost(requestParameters: ApiV1FcmDevicePostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1FcmDevicePostRaw(requestParameters, initOverrides);
    }

}
