/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiV1ChatChatGUIDParticipantPostRequest,
} from '../models/index';
import {
    ApiV1ChatChatGUIDParticipantPostRequestFromJSON,
    ApiV1ChatChatGUIDParticipantPostRequestToJSON,
} from '../models/index';

export interface ApiV1ChatChatGUIDIconDeleteRequest {
    password?: string;
}

export interface ApiV1ChatChatGUIDIconPostRequest {
    password?: string;
}

export interface ApiV1ChatChatGUIDLeavePostRequest {
    password?: string;
    body?: object;
}

export interface ApiV1ChatChatGUIDParticipantDeleteRequest {
    password?: string;
    apiV1ChatChatGUIDParticipantPostRequest?: ApiV1ChatChatGUIDParticipantPostRequest;
}

export interface ApiV1ChatChatGUIDParticipantPostOperationRequest {
    password?: string;
    apiV1ChatChatGUIDParticipantPostRequest?: ApiV1ChatChatGUIDParticipantPostRequest;
}

/**
 * GroupSpecificApi - interface
 * 
 * @export
 * @interface GroupSpecificApiInterface
 */
export interface GroupSpecificApiInterface {
    /**
     * Removes/Unsets a group chat\'s icon/photo.  **Requires:** Private API
     * @summary Remove Group Icon
     * @param {string} [password] Your BlueBubbles Server password
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupSpecificApiInterface
     */
    apiV1ChatChatGUIDIconDeleteRaw(requestParameters: ApiV1ChatChatGUIDIconDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Removes/Unsets a group chat\'s icon/photo.  **Requires:** Private API
     * Remove Group Icon
     */
    apiV1ChatChatGUIDIconDelete(requestParameters: ApiV1ChatChatGUIDIconDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Set a group chat\'s icon/photo.  **Requires:** Private API
     * @summary Set Group Icon
     * @param {string} [password] Your BlueBubbles Server password
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupSpecificApiInterface
     */
    apiV1ChatChatGUIDIconPostRaw(requestParameters: ApiV1ChatChatGUIDIconPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Set a group chat\'s icon/photo.  **Requires:** Private API
     * Set Group Icon
     */
    apiV1ChatChatGUIDIconPost(requestParameters: ApiV1ChatChatGUIDIconPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Allows you to leave a group chat that you are in.  An error will be thrown if the chat you are trying to leave is not a group chat.  **Requires:** Private API
     * @summary Leave Chat
     * @param {string} [password] Your BlueBubbles Server password
     * @param {object} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupSpecificApiInterface
     */
    apiV1ChatChatGUIDLeavePostRaw(requestParameters: ApiV1ChatChatGUIDLeavePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Allows you to leave a group chat that you are in.  An error will be thrown if the chat you are trying to leave is not a group chat.  **Requires:** Private API
     * Leave Chat
     */
    apiV1ChatChatGUIDLeavePost(requestParameters: ApiV1ChatChatGUIDLeavePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Removes a participant from an existing chat  **Minimum BlueBubbles Server Version**: 0.3.0  **Requires:** Private API  #### Request Body  ```json {     // The participant address to remove     \"address\": \"\" } ```
     * @summary Remove Participant from Chat
     * @param {string} [password] Your BlueBubbles Server password
     * @param {ApiV1ChatChatGUIDParticipantPostRequest} [apiV1ChatChatGUIDParticipantPostRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupSpecificApiInterface
     */
    apiV1ChatChatGUIDParticipantDeleteRaw(requestParameters: ApiV1ChatChatGUIDParticipantDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Removes a participant from an existing chat  **Minimum BlueBubbles Server Version**: 0.3.0  **Requires:** Private API  #### Request Body  ```json {     // The participant address to remove     \"address\": \"\" } ```
     * Remove Participant from Chat
     */
    apiV1ChatChatGUIDParticipantDelete(requestParameters: ApiV1ChatChatGUIDParticipantDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Adds a participant to an existing chat.  Include the country code (if possible). For instance, the country code for the United States is `+1`, so include a `1` at the start of the phone number from the US.  **Minimum BlueBubbles Server Version**: 0.3.0  **Requires:** Private API  #### Request Body  ``` json {     // The participant address to add     \"address\": \"\" }  ```
     * @summary Add Participant to Chat
     * @param {string} [password] Your BlueBubbles Server password
     * @param {ApiV1ChatChatGUIDParticipantPostRequest} [apiV1ChatChatGUIDParticipantPostRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupSpecificApiInterface
     */
    apiV1ChatChatGUIDParticipantPostRaw(requestParameters: ApiV1ChatChatGUIDParticipantPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Adds a participant to an existing chat.  Include the country code (if possible). For instance, the country code for the United States is `+1`, so include a `1` at the start of the phone number from the US.  **Minimum BlueBubbles Server Version**: 0.3.0  **Requires:** Private API  #### Request Body  ``` json {     // The participant address to add     \"address\": \"\" }  ```
     * Add Participant to Chat
     */
    apiV1ChatChatGUIDParticipantPost(requestParameters: ApiV1ChatChatGUIDParticipantPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class GroupSpecificApi extends runtime.BaseAPI implements GroupSpecificApiInterface {

    /**
     * Removes/Unsets a group chat\'s icon/photo.  **Requires:** Private API
     * Remove Group Icon
     */
    async apiV1ChatChatGUIDIconDeleteRaw(requestParameters: ApiV1ChatChatGUIDIconDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/chat/<Chat GUID>/icon`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes/Unsets a group chat\'s icon/photo.  **Requires:** Private API
     * Remove Group Icon
     */
    async apiV1ChatChatGUIDIconDelete(requestParameters: ApiV1ChatChatGUIDIconDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1ChatChatGUIDIconDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Set a group chat\'s icon/photo.  **Requires:** Private API
     * Set Group Icon
     */
    async apiV1ChatChatGUIDIconPostRaw(requestParameters: ApiV1ChatChatGUIDIconPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/chat/<Chat GUID>/icon`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Set a group chat\'s icon/photo.  **Requires:** Private API
     * Set Group Icon
     */
    async apiV1ChatChatGUIDIconPost(requestParameters: ApiV1ChatChatGUIDIconPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1ChatChatGUIDIconPostRaw(requestParameters, initOverrides);
    }

    /**
     * Allows you to leave a group chat that you are in.  An error will be thrown if the chat you are trying to leave is not a group chat.  **Requires:** Private API
     * Leave Chat
     */
    async apiV1ChatChatGUIDLeavePostRaw(requestParameters: ApiV1ChatChatGUIDLeavePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/chat/<Chat GUID>/leave`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Allows you to leave a group chat that you are in.  An error will be thrown if the chat you are trying to leave is not a group chat.  **Requires:** Private API
     * Leave Chat
     */
    async apiV1ChatChatGUIDLeavePost(requestParameters: ApiV1ChatChatGUIDLeavePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1ChatChatGUIDLeavePostRaw(requestParameters, initOverrides);
    }

    /**
     * Removes a participant from an existing chat  **Minimum BlueBubbles Server Version**: 0.3.0  **Requires:** Private API  #### Request Body  ```json {     // The participant address to remove     \"address\": \"\" } ```
     * Remove Participant from Chat
     */
    async apiV1ChatChatGUIDParticipantDeleteRaw(requestParameters: ApiV1ChatChatGUIDParticipantDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/chat/<Chat GUID>/participant`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: ApiV1ChatChatGUIDParticipantPostRequestToJSON(requestParameters['apiV1ChatChatGUIDParticipantPostRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes a participant from an existing chat  **Minimum BlueBubbles Server Version**: 0.3.0  **Requires:** Private API  #### Request Body  ```json {     // The participant address to remove     \"address\": \"\" } ```
     * Remove Participant from Chat
     */
    async apiV1ChatChatGUIDParticipantDelete(requestParameters: ApiV1ChatChatGUIDParticipantDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1ChatChatGUIDParticipantDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Adds a participant to an existing chat.  Include the country code (if possible). For instance, the country code for the United States is `+1`, so include a `1` at the start of the phone number from the US.  **Minimum BlueBubbles Server Version**: 0.3.0  **Requires:** Private API  #### Request Body  ``` json {     // The participant address to add     \"address\": \"\" }  ```
     * Add Participant to Chat
     */
    async apiV1ChatChatGUIDParticipantPostRaw(requestParameters: ApiV1ChatChatGUIDParticipantPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/chat/<Chat GUID>/participant`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiV1ChatChatGUIDParticipantPostRequestToJSON(requestParameters['apiV1ChatChatGUIDParticipantPostRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Adds a participant to an existing chat.  Include the country code (if possible). For instance, the country code for the United States is `+1`, so include a `1` at the start of the phone number from the US.  **Minimum BlueBubbles Server Version**: 0.3.0  **Requires:** Private API  #### Request Body  ``` json {     // The participant address to add     \"address\": \"\" }  ```
     * Add Participant to Chat
     */
    async apiV1ChatChatGUIDParticipantPost(requestParameters: ApiV1ChatChatGUIDParticipantPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1ChatChatGUIDParticipantPostRaw(requestParameters, initOverrides);
    }

}
