/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiV1HandleQueryPostRequest,
} from '../models/index';
import {
    ApiV1HandleQueryPostRequestFromJSON,
    ApiV1HandleQueryPostRequestToJSON,
} from '../models/index';

export interface ApiV1HandleAddressFocusGetRequest {
    password?: string;
}

export interface ApiV1HandleAvailabilityFacetimeGetRequest {
    password?: string;
    address?: string;
}

export interface ApiV1HandleAvailabilityImessageGetRequest {
    password?: string;
    address?: string;
}

export interface ApiV1HandleCountGetRequest {
    password?: string;
}

export interface ApiV1HandleHandleAddressGetRequest {
    password?: string;
}

export interface ApiV1HandleQueryPostOperationRequest {
    password?: string;
    apiV1HandleQueryPostRequest?: ApiV1HandleQueryPostRequest;
}

/**
 * HandleApi - interface
 * 
 * @export
 * @interface HandleApiInterface
 */
export interface HandleApiInterface {
    /**
     * Get the handle\'s focus mode status.  Return values include:  - unknown - silenced - none
     * @summary Get Handle\'s Focus Status
     * @param {string} [password] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HandleApiInterface
     */
    apiV1HandleAddressFocusGetRaw(requestParameters: ApiV1HandleAddressFocusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Get the handle\'s focus mode status.  Return values include:  - unknown - silenced - none
     * Get Handle\'s Focus Status
     */
    apiV1HandleAddressFocusGet(requestParameters: ApiV1HandleAddressFocusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Checks if a given address has FaceTime enabled for it.
     * @summary Get FaceTimeAvailability
     * @param {string} [password] 
     * @param {string} [address] Required. The address to check if it has FaceTime activated
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HandleApiInterface
     */
    apiV1HandleAvailabilityFacetimeGetRaw(requestParameters: ApiV1HandleAvailabilityFacetimeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Checks if a given address has FaceTime enabled for it.
     * Get FaceTimeAvailability
     */
    apiV1HandleAvailabilityFacetimeGet(requestParameters: ApiV1HandleAvailabilityFacetimeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Checks if a given address has iMessage enabled for it.
     * @summary Get iMessage Availability
     * @param {string} [password] 
     * @param {string} [address] Required. The address to check if it has iMessage activated
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HandleApiInterface
     */
    apiV1HandleAvailabilityImessageGetRaw(requestParameters: ApiV1HandleAvailabilityImessageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Checks if a given address has iMessage enabled for it.
     * Get iMessage Availability
     */
    apiV1HandleAvailabilityImessageGet(requestParameters: ApiV1HandleAvailabilityImessageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Get the total number of handles for your iMessage account (on the device)
     * @summary Get Handle Count
     * @param {string} [password] Your BlueBubbles Server password
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HandleApiInterface
     */
    apiV1HandleCountGetRaw(requestParameters: ApiV1HandleCountGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Get the total number of handles for your iMessage account (on the device)
     * Get Handle Count
     */
    apiV1HandleCountGet(requestParameters: ApiV1HandleCountGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Fetch a Handle\'s database information by Address (email or phone number)
     * @summary Get Handle by Address
     * @param {string} [password] Your BlueBubbles Server password
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HandleApiInterface
     */
    apiV1HandleHandleAddressGetRaw(requestParameters: ApiV1HandleHandleAddressGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Fetch a Handle\'s database information by Address (email or phone number)
     * Get Handle by Address
     */
    apiV1HandleHandleAddressGet(requestParameters: ApiV1HandleHandleAddressGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Query for Chats from the database  #### Request Body  ```json {     // (Optional) A number representing the offset for the database query.     // This is useful for paging through data from the database to make database calls return as quick as possible.     // (Default: 0)     \"limit\": 1000,     //( Optional) A number representing the offset for the database query.     // This is useful for paging through data from the database to make database calls return as quick as possible.     // (Default: 0)     \"offset\": 0,     // (Optional) What related information do you want returned with the messages?     // Must be one of: `participants`, `lastmessage`, `sms`, `archived`     \"with\": [         \"lastMessage\",         \"participants\",         \"sms\",         \"archived\"     ],     // (Optional) How the returned data should be sorted.     // In order to sort, `lastmessage` must be included in the `with` parameter.     // Must be: `lastmessage`     \"sort\": \"lastmessage\" } ```
     * @summary Query Handles
     * @param {string} [password] Your BlueBubbles Server password
     * @param {ApiV1HandleQueryPostRequest} [apiV1HandleQueryPostRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HandleApiInterface
     */
    apiV1HandleQueryPostRaw(requestParameters: ApiV1HandleQueryPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Query for Chats from the database  #### Request Body  ```json {     // (Optional) A number representing the offset for the database query.     // This is useful for paging through data from the database to make database calls return as quick as possible.     // (Default: 0)     \"limit\": 1000,     //( Optional) A number representing the offset for the database query.     // This is useful for paging through data from the database to make database calls return as quick as possible.     // (Default: 0)     \"offset\": 0,     // (Optional) What related information do you want returned with the messages?     // Must be one of: `participants`, `lastmessage`, `sms`, `archived`     \"with\": [         \"lastMessage\",         \"participants\",         \"sms\",         \"archived\"     ],     // (Optional) How the returned data should be sorted.     // In order to sort, `lastmessage` must be included in the `with` parameter.     // Must be: `lastmessage`     \"sort\": \"lastmessage\" } ```
     * Query Handles
     */
    apiV1HandleQueryPost(requestParameters: ApiV1HandleQueryPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class HandleApi extends runtime.BaseAPI implements HandleApiInterface {

    /**
     * Get the handle\'s focus mode status.  Return values include:  - unknown - silenced - none
     * Get Handle\'s Focus Status
     */
    async apiV1HandleAddressFocusGetRaw(requestParameters: ApiV1HandleAddressFocusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/handle/<address>/focus`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get the handle\'s focus mode status.  Return values include:  - unknown - silenced - none
     * Get Handle\'s Focus Status
     */
    async apiV1HandleAddressFocusGet(requestParameters: ApiV1HandleAddressFocusGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1HandleAddressFocusGetRaw(requestParameters, initOverrides);
    }

    /**
     * Checks if a given address has FaceTime enabled for it.
     * Get FaceTimeAvailability
     */
    async apiV1HandleAvailabilityFacetimeGetRaw(requestParameters: ApiV1HandleAvailabilityFacetimeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/handle/availability/facetime`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Checks if a given address has FaceTime enabled for it.
     * Get FaceTimeAvailability
     */
    async apiV1HandleAvailabilityFacetimeGet(requestParameters: ApiV1HandleAvailabilityFacetimeGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1HandleAvailabilityFacetimeGetRaw(requestParameters, initOverrides);
    }

    /**
     * Checks if a given address has iMessage enabled for it.
     * Get iMessage Availability
     */
    async apiV1HandleAvailabilityImessageGetRaw(requestParameters: ApiV1HandleAvailabilityImessageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/handle/availability/imessage`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Checks if a given address has iMessage enabled for it.
     * Get iMessage Availability
     */
    async apiV1HandleAvailabilityImessageGet(requestParameters: ApiV1HandleAvailabilityImessageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1HandleAvailabilityImessageGetRaw(requestParameters, initOverrides);
    }

    /**
     * Get the total number of handles for your iMessage account (on the device)
     * Get Handle Count
     */
    async apiV1HandleCountGetRaw(requestParameters: ApiV1HandleCountGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/handle/count`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get the total number of handles for your iMessage account (on the device)
     * Get Handle Count
     */
    async apiV1HandleCountGet(requestParameters: ApiV1HandleCountGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1HandleCountGetRaw(requestParameters, initOverrides);
    }

    /**
     * Fetch a Handle\'s database information by Address (email or phone number)
     * Get Handle by Address
     */
    async apiV1HandleHandleAddressGetRaw(requestParameters: ApiV1HandleHandleAddressGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/handle/<Handle Address>`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Fetch a Handle\'s database information by Address (email or phone number)
     * Get Handle by Address
     */
    async apiV1HandleHandleAddressGet(requestParameters: ApiV1HandleHandleAddressGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1HandleHandleAddressGetRaw(requestParameters, initOverrides);
    }

    /**
     * Query for Chats from the database  #### Request Body  ```json {     // (Optional) A number representing the offset for the database query.     // This is useful for paging through data from the database to make database calls return as quick as possible.     // (Default: 0)     \"limit\": 1000,     //( Optional) A number representing the offset for the database query.     // This is useful for paging through data from the database to make database calls return as quick as possible.     // (Default: 0)     \"offset\": 0,     // (Optional) What related information do you want returned with the messages?     // Must be one of: `participants`, `lastmessage`, `sms`, `archived`     \"with\": [         \"lastMessage\",         \"participants\",         \"sms\",         \"archived\"     ],     // (Optional) How the returned data should be sorted.     // In order to sort, `lastmessage` must be included in the `with` parameter.     // Must be: `lastmessage`     \"sort\": \"lastmessage\" } ```
     * Query Handles
     */
    async apiV1HandleQueryPostRaw(requestParameters: ApiV1HandleQueryPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/handle/query`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiV1HandleQueryPostRequestToJSON(requestParameters['apiV1HandleQueryPostRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Query for Chats from the database  #### Request Body  ```json {     // (Optional) A number representing the offset for the database query.     // This is useful for paging through data from the database to make database calls return as quick as possible.     // (Default: 0)     \"limit\": 1000,     //( Optional) A number representing the offset for the database query.     // This is useful for paging through data from the database to make database calls return as quick as possible.     // (Default: 0)     \"offset\": 0,     // (Optional) What related information do you want returned with the messages?     // Must be one of: `participants`, `lastmessage`, `sms`, `archived`     \"with\": [         \"lastMessage\",         \"participants\",         \"sms\",         \"archived\"     ],     // (Optional) How the returned data should be sorted.     // In order to sort, `lastmessage` must be included in the `with` parameter.     // Must be: `lastmessage`     \"sort\": \"lastmessage\" } ```
     * Query Handles
     */
    async apiV1HandleQueryPost(requestParameters: ApiV1HandleQueryPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1HandleQueryPostRaw(requestParameters, initOverrides);
    }

}
