/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiV1MacLockPost200Response,
} from '../models/index';
import {
    ApiV1MacLockPost200ResponseFromJSON,
    ApiV1MacLockPost200ResponseToJSON,
} from '../models/index';

export interface ApiV1MacLockPostRequest {
    password?: string;
}

/**
 * MacOSApi - interface
 * 
 * @export
 * @interface MacOSApiInterface
 */
export interface MacOSApiInterface {
    /**
     * Lock your macOS device directly via the API. This endpoint can be useful if you believe your macOS device has been compromised. Locking it will prevent the adversary from accessing your account. This will not log you out, but will lock your account.
     * @summary Lock Mac
     * @param {string} [password] Your BlueBubbles Server password
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MacOSApiInterface
     */
    apiV1MacLockPostRaw(requestParameters: ApiV1MacLockPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1MacLockPost200Response>>;

    /**
     * Lock your macOS device directly via the API. This endpoint can be useful if you believe your macOS device has been compromised. Locking it will prevent the adversary from accessing your account. This will not log you out, but will lock your account.
     * Lock Mac
     */
    apiV1MacLockPost(requestParameters: ApiV1MacLockPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1MacLockPost200Response>;

}

/**
 * 
 */
export class MacOSApi extends runtime.BaseAPI implements MacOSApiInterface {

    /**
     * Lock your macOS device directly via the API. This endpoint can be useful if you believe your macOS device has been compromised. Locking it will prevent the adversary from accessing your account. This will not log you out, but will lock your account.
     * Lock Mac
     */
    async apiV1MacLockPostRaw(requestParameters: ApiV1MacLockPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1MacLockPost200Response>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/mac/lock`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1MacLockPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Lock your macOS device directly via the API. This endpoint can be useful if you believe your macOS device has been compromised. Locking it will prevent the adversary from accessing your account. This will not log you out, but will lock your account.
     * Lock Mac
     */
    async apiV1MacLockPost(requestParameters: ApiV1MacLockPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1MacLockPost200Response> {
        const response = await this.apiV1MacLockPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
