/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface ApiV1PingGetRequest {
    password?: string;
}

/**
 * OtherApi - interface
 * 
 * @export
 * @interface OtherApiInterface
 */
export interface OtherApiInterface {
    /**
     * Send a quick ping to your BlueBubbles Server to make sure it\'s online and responding to requests
     * @summary Ping
     * @param {string} [password] Your BlueBubbles Server password
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OtherApiInterface
     */
    apiV1PingGetRaw(requestParameters: ApiV1PingGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Send a quick ping to your BlueBubbles Server to make sure it\'s online and responding to requests
     * Ping
     */
    apiV1PingGet(requestParameters: ApiV1PingGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class OtherApi extends runtime.BaseAPI implements OtherApiInterface {

    /**
     * Send a quick ping to your BlueBubbles Server to make sure it\'s online and responding to requests
     * Ping
     */
    async apiV1PingGetRaw(requestParameters: ApiV1PingGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/ping`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Send a quick ping to your BlueBubbles Server to make sure it\'s online and responding to requests
     * Ping
     */
    async apiV1PingGet(requestParameters: ApiV1PingGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1PingGetRaw(requestParameters, initOverrides);
    }

}
