/* tslint:disable */
/* eslint-disable */
/**
 * BlueBubbles
 * This is the API Documentation for the BlueBubbles Server App\'s REST API.  > This OpenAPI 3.0 spec was generated from the official BlueBubbles Postman collection: https://documenter.getpostman.com/view/765844/UV5RnfwM  ## What is BlueBubbles  BlueBubbles is a cross-platform app ecosystem aimed to bring iMessage to all your devices. This means, as long as you have a macOS device/deployment running the BlueBubbles Server App, you\'ll be able to send and receive iMessages.  ## What does this API offer?  This API offers abilities to store backups of settings/themes, as well as interacting with the underlying macOS device. You\'ll be able to fetch chats, messages, attachments, handles, as well as receive notifications via sockets (Socket.IO; I want to change this in the future...)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiV1ServerAlertReadPostRequest,
  ApiV1ServerInfoGet200Response,
  ApiV1ServerLogsGet200Response,
  ApiV1ServerStatisticsMediaChatGet200Response,
  ApiV1ServerStatisticsMediaGet200Response,
  ApiV1ServerStatisticsTotalsGet200Response,
  ApiV1ServerUpdateCheckGet200Response,
} from '../models/index';
import {
    ApiV1ServerAlertReadPostRequestFromJSON,
    ApiV1ServerAlertReadPostRequestToJSON,
    ApiV1ServerInfoGet200ResponseFromJSON,
    ApiV1ServerInfoGet200ResponseToJSON,
    ApiV1ServerLogsGet200ResponseFromJSON,
    ApiV1ServerLogsGet200ResponseToJSON,
    ApiV1ServerStatisticsMediaChatGet200ResponseFromJSON,
    ApiV1ServerStatisticsMediaChatGet200ResponseToJSON,
    ApiV1ServerStatisticsMediaGet200ResponseFromJSON,
    ApiV1ServerStatisticsMediaGet200ResponseToJSON,
    ApiV1ServerStatisticsTotalsGet200ResponseFromJSON,
    ApiV1ServerStatisticsTotalsGet200ResponseToJSON,
    ApiV1ServerUpdateCheckGet200ResponseFromJSON,
    ApiV1ServerUpdateCheckGet200ResponseToJSON,
} from '../models/index';

export interface ApiV1ServerAlertGetRequest {
    password?: string;
}

export interface ApiV1ServerAlertReadPostOperationRequest {
    password?: string;
    apiV1ServerAlertReadPostRequest?: ApiV1ServerAlertReadPostRequest;
}

export interface ApiV1ServerInfoGetRequest {
    password?: string;
}

export interface ApiV1ServerLogsGetRequest {
    password?: string;
    count?: number;
}

export interface ApiV1ServerRestartHardGetRequest {
    password?: string;
}

export interface ApiV1ServerRestartSoftGetRequest {
    password?: string;
}

export interface ApiV1ServerStatisticsMediaChatGetRequest {
    password?: string;
    only?: string;
}

export interface ApiV1ServerStatisticsMediaGetRequest {
    password?: string;
    only?: string;
}

export interface ApiV1ServerStatisticsTotalsGetRequest {
    password?: string;
    only?: string;
}

export interface ApiV1ServerUpdateCheckGetRequest {
    password?: string;
}

export interface ApiV1ServerUpdateInstallPostRequest {
    password?: string;
    wait?: boolean;
}

/**
 * ServerApi - interface
 * 
 * @export
 * @interface ServerApiInterface
 */
export interface ServerApiInterface {
    /**
     * Fetch logs from your BlueBubbles Server.
     * @summary Get Alerts
     * @param {string} [password] Your BlueBubbles Server password
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServerApiInterface
     */
    apiV1ServerAlertGetRaw(requestParameters: ApiV1ServerAlertGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ServerLogsGet200Response>>;

    /**
     * Fetch logs from your BlueBubbles Server.
     * Get Alerts
     */
    apiV1ServerAlertGet(requestParameters: ApiV1ServerAlertGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ServerLogsGet200Response>;

    /**
     * Marks alerts as read based on the provided IDs
     * @summary Mark Alert as Read
     * @param {string} [password] Your BlueBubbles Server password
     * @param {ApiV1ServerAlertReadPostRequest} [apiV1ServerAlertReadPostRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServerApiInterface
     */
    apiV1ServerAlertReadPostRaw(requestParameters: ApiV1ServerAlertReadPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ServerUpdateCheckGet200Response>>;

    /**
     * Marks alerts as read based on the provided IDs
     * Mark Alert as Read
     */
    apiV1ServerAlertReadPost(requestParameters: ApiV1ServerAlertReadPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ServerUpdateCheckGet200Response>;

    /**
     * Fetch metadata about your BlueBubbles Server & Operating System
     * @summary Get Server Metadata
     * @param {string} [password] Your BlueBubbles Server password
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServerApiInterface
     */
    apiV1ServerInfoGetRaw(requestParameters: ApiV1ServerInfoGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ServerInfoGet200Response>>;

    /**
     * Fetch metadata about your BlueBubbles Server & Operating System
     * Get Server Metadata
     */
    apiV1ServerInfoGet(requestParameters: ApiV1ServerInfoGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ServerInfoGet200Response>;

    /**
     * Fetch logs from your BlueBubbles Server.
     * @summary Get Server Logs
     * @param {string} [password] Your BlueBubbles Server password
     * @param {number} [count] (Optional) The number of logs to fetch (starting from the most recent). Default: 100
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServerApiInterface
     */
    apiV1ServerLogsGetRaw(requestParameters: ApiV1ServerLogsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ServerLogsGet200Response>>;

    /**
     * Fetch logs from your BlueBubbles Server.
     * Get Server Logs
     */
    apiV1ServerLogsGet(requestParameters: ApiV1ServerLogsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ServerLogsGet200Response>;

    /**
     * Completely restarts the server. Meaning the server closes itself and reopens itself. The Mac will not restart.
     * @summary Restart Server
     * @param {string} [password] Your BlueBubbles Server password
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServerApiInterface
     */
    apiV1ServerRestartHardGetRaw(requestParameters: ApiV1ServerRestartHardGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ServerLogsGet200Response>>;

    /**
     * Completely restarts the server. Meaning the server closes itself and reopens itself. The Mac will not restart.
     * Restart Server
     */
    apiV1ServerRestartHardGet(requestParameters: ApiV1ServerRestartHardGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ServerLogsGet200Response>;

    /**
     * Restarts the services on the BlueBubbles server. Services such as the HTTP service, the FCM service, and the Private API service.
     * @summary Restart Services
     * @param {string} [password] Your BlueBubbles Server password
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServerApiInterface
     */
    apiV1ServerRestartSoftGetRaw(requestParameters: ApiV1ServerRestartSoftGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ServerLogsGet200Response>>;

    /**
     * Restarts the services on the BlueBubbles server. Services such as the HTTP service, the FCM service, and the Private API service.
     * Restart Services
     */
    apiV1ServerRestartSoftGet(requestParameters: ApiV1ServerRestartSoftGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ServerLogsGet200Response>;

    /**
     * Fetches different types of media totals per chat (i.e. videos & images).
     * @summary Get Media Totals Per Chat
     * @param {string} [password] Your BlueBubbles Server password
     * @param {string} [only] (Optional) A parameter telling the API which totals to calculate. Must be one of: &#x60;video&#x60;, &#x60;image&#x60;, &#x60;location&#x60; (Default: All)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServerApiInterface
     */
    apiV1ServerStatisticsMediaChatGetRaw(requestParameters: ApiV1ServerStatisticsMediaChatGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ServerStatisticsMediaChatGet200Response>>;

    /**
     * Fetches different types of media totals per chat (i.e. videos & images).
     * Get Media Totals Per Chat
     */
    apiV1ServerStatisticsMediaChatGet(requestParameters: ApiV1ServerStatisticsMediaChatGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ServerStatisticsMediaChatGet200Response>;

    /**
     * Fetches different types of media totals for all chats (i.e. videos & images).
     * @summary Get Media Totals
     * @param {string} [password] Your BlueBubbles Server password
     * @param {string} [only] (Optional) A parameter telling the API which totals to calculate. Must be one of: &#x60;video&#x60;, &#x60;image&#x60;, &#x60;location&#x60; (Default: All)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServerApiInterface
     */
    apiV1ServerStatisticsMediaGetRaw(requestParameters: ApiV1ServerStatisticsMediaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ServerStatisticsMediaGet200Response>>;

    /**
     * Fetches different types of media totals for all chats (i.e. videos & images).
     * Get Media Totals
     */
    apiV1ServerStatisticsMediaGet(requestParameters: ApiV1ServerStatisticsMediaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ServerStatisticsMediaGet200Response>;

    /**
     * Fetches the database totals for the iMessage entities (i.e. handles, messages, chats, etc.)
     * @summary Get iMessage Entity Totals
     * @param {string} [password] Your BlueBubbles Server password
     * @param {string} [only] (Optional) A parameter telling the API which totals to calculate. Must be one of: &#x60;handle&#x60;, &#x60;message&#x60;, &#x60;chat&#x60;, &#x60;attachment&#x60; (Default: All)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServerApiInterface
     */
    apiV1ServerStatisticsTotalsGetRaw(requestParameters: ApiV1ServerStatisticsTotalsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ServerStatisticsTotalsGet200Response>>;

    /**
     * Fetches the database totals for the iMessage entities (i.e. handles, messages, chats, etc.)
     * Get iMessage Entity Totals
     */
    apiV1ServerStatisticsTotalsGet(requestParameters: ApiV1ServerStatisticsTotalsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ServerStatisticsTotalsGet200Response>;

    /**
     * Check to see if the BlueBubbles Server App has an update available. If an update is available, the update metadata will be returned.
     * @summary Check for Server Update
     * @param {string} [password] Your BlueBubbles Server password
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServerApiInterface
     */
    apiV1ServerUpdateCheckGetRaw(requestParameters: ApiV1ServerUpdateCheckGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ServerUpdateCheckGet200Response>>;

    /**
     * Check to see if the BlueBubbles Server App has an update available. If an update is available, the update metadata will be returned.
     * Check for Server Update
     */
    apiV1ServerUpdateCheckGet(requestParameters: ApiV1ServerUpdateCheckGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ServerUpdateCheckGet200Response>;

    /**
     * Installs an update if one is available.  You may pass a `wait=true` URL parameter to have the endpoint wait until the update is complete to return. Otherwise, it will not by default.
     * @summary Install Server Update
     * @param {string} [password] Your BlueBubbles Server password
     * @param {boolean} [wait] (Optional) Waits for the update to complete to return (default: false)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServerApiInterface
     */
    apiV1ServerUpdateInstallPostRaw(requestParameters: ApiV1ServerUpdateInstallPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ServerUpdateCheckGet200Response>>;

    /**
     * Installs an update if one is available.  You may pass a `wait=true` URL parameter to have the endpoint wait until the update is complete to return. Otherwise, it will not by default.
     * Install Server Update
     */
    apiV1ServerUpdateInstallPost(requestParameters: ApiV1ServerUpdateInstallPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ServerUpdateCheckGet200Response>;

}

/**
 * 
 */
export class ServerApi extends runtime.BaseAPI implements ServerApiInterface {

    /**
     * Fetch logs from your BlueBubbles Server.
     * Get Alerts
     */
    async apiV1ServerAlertGetRaw(requestParameters: ApiV1ServerAlertGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ServerLogsGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/server/alert`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1ServerLogsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Fetch logs from your BlueBubbles Server.
     * Get Alerts
     */
    async apiV1ServerAlertGet(requestParameters: ApiV1ServerAlertGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ServerLogsGet200Response> {
        const response = await this.apiV1ServerAlertGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Marks alerts as read based on the provided IDs
     * Mark Alert as Read
     */
    async apiV1ServerAlertReadPostRaw(requestParameters: ApiV1ServerAlertReadPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ServerUpdateCheckGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/server/alert/read`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiV1ServerAlertReadPostRequestToJSON(requestParameters['apiV1ServerAlertReadPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1ServerUpdateCheckGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Marks alerts as read based on the provided IDs
     * Mark Alert as Read
     */
    async apiV1ServerAlertReadPost(requestParameters: ApiV1ServerAlertReadPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ServerUpdateCheckGet200Response> {
        const response = await this.apiV1ServerAlertReadPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fetch metadata about your BlueBubbles Server & Operating System
     * Get Server Metadata
     */
    async apiV1ServerInfoGetRaw(requestParameters: ApiV1ServerInfoGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ServerInfoGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/server/info`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1ServerInfoGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Fetch metadata about your BlueBubbles Server & Operating System
     * Get Server Metadata
     */
    async apiV1ServerInfoGet(requestParameters: ApiV1ServerInfoGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ServerInfoGet200Response> {
        const response = await this.apiV1ServerInfoGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fetch logs from your BlueBubbles Server.
     * Get Server Logs
     */
    async apiV1ServerLogsGetRaw(requestParameters: ApiV1ServerLogsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ServerLogsGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        if (requestParameters['count'] != null) {
            queryParameters['count'] = requestParameters['count'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/server/logs`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1ServerLogsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Fetch logs from your BlueBubbles Server.
     * Get Server Logs
     */
    async apiV1ServerLogsGet(requestParameters: ApiV1ServerLogsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ServerLogsGet200Response> {
        const response = await this.apiV1ServerLogsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Completely restarts the server. Meaning the server closes itself and reopens itself. The Mac will not restart.
     * Restart Server
     */
    async apiV1ServerRestartHardGetRaw(requestParameters: ApiV1ServerRestartHardGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ServerLogsGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/server/restart/hard`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1ServerLogsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Completely restarts the server. Meaning the server closes itself and reopens itself. The Mac will not restart.
     * Restart Server
     */
    async apiV1ServerRestartHardGet(requestParameters: ApiV1ServerRestartHardGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ServerLogsGet200Response> {
        const response = await this.apiV1ServerRestartHardGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Restarts the services on the BlueBubbles server. Services such as the HTTP service, the FCM service, and the Private API service.
     * Restart Services
     */
    async apiV1ServerRestartSoftGetRaw(requestParameters: ApiV1ServerRestartSoftGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ServerLogsGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/server/restart/soft`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1ServerLogsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Restarts the services on the BlueBubbles server. Services such as the HTTP service, the FCM service, and the Private API service.
     * Restart Services
     */
    async apiV1ServerRestartSoftGet(requestParameters: ApiV1ServerRestartSoftGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ServerLogsGet200Response> {
        const response = await this.apiV1ServerRestartSoftGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fetches different types of media totals per chat (i.e. videos & images).
     * Get Media Totals Per Chat
     */
    async apiV1ServerStatisticsMediaChatGetRaw(requestParameters: ApiV1ServerStatisticsMediaChatGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ServerStatisticsMediaChatGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        if (requestParameters['only'] != null) {
            queryParameters['only'] = requestParameters['only'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/server/statistics/media/chat`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1ServerStatisticsMediaChatGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Fetches different types of media totals per chat (i.e. videos & images).
     * Get Media Totals Per Chat
     */
    async apiV1ServerStatisticsMediaChatGet(requestParameters: ApiV1ServerStatisticsMediaChatGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ServerStatisticsMediaChatGet200Response> {
        const response = await this.apiV1ServerStatisticsMediaChatGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fetches different types of media totals for all chats (i.e. videos & images).
     * Get Media Totals
     */
    async apiV1ServerStatisticsMediaGetRaw(requestParameters: ApiV1ServerStatisticsMediaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ServerStatisticsMediaGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        if (requestParameters['only'] != null) {
            queryParameters['only'] = requestParameters['only'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/server/statistics/media`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1ServerStatisticsMediaGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Fetches different types of media totals for all chats (i.e. videos & images).
     * Get Media Totals
     */
    async apiV1ServerStatisticsMediaGet(requestParameters: ApiV1ServerStatisticsMediaGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ServerStatisticsMediaGet200Response> {
        const response = await this.apiV1ServerStatisticsMediaGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fetches the database totals for the iMessage entities (i.e. handles, messages, chats, etc.)
     * Get iMessage Entity Totals
     */
    async apiV1ServerStatisticsTotalsGetRaw(requestParameters: ApiV1ServerStatisticsTotalsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ServerStatisticsTotalsGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        if (requestParameters['only'] != null) {
            queryParameters['only'] = requestParameters['only'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/server/statistics/totals`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1ServerStatisticsTotalsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Fetches the database totals for the iMessage entities (i.e. handles, messages, chats, etc.)
     * Get iMessage Entity Totals
     */
    async apiV1ServerStatisticsTotalsGet(requestParameters: ApiV1ServerStatisticsTotalsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ServerStatisticsTotalsGet200Response> {
        const response = await this.apiV1ServerStatisticsTotalsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Check to see if the BlueBubbles Server App has an update available. If an update is available, the update metadata will be returned.
     * Check for Server Update
     */
    async apiV1ServerUpdateCheckGetRaw(requestParameters: ApiV1ServerUpdateCheckGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ServerUpdateCheckGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/server/update/check`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1ServerUpdateCheckGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Check to see if the BlueBubbles Server App has an update available. If an update is available, the update metadata will be returned.
     * Check for Server Update
     */
    async apiV1ServerUpdateCheckGet(requestParameters: ApiV1ServerUpdateCheckGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ServerUpdateCheckGet200Response> {
        const response = await this.apiV1ServerUpdateCheckGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Installs an update if one is available.  You may pass a `wait=true` URL parameter to have the endpoint wait until the update is complete to return. Otherwise, it will not by default.
     * Install Server Update
     */
    async apiV1ServerUpdateInstallPostRaw(requestParameters: ApiV1ServerUpdateInstallPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1ServerUpdateCheckGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        if (requestParameters['wait'] != null) {
            queryParameters['wait'] = requestParameters['wait'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/server/update/install`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1ServerUpdateCheckGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Installs an update if one is available.  You may pass a `wait=true` URL parameter to have the endpoint wait until the update is complete to return. Otherwise, it will not by default.
     * Install Server Update
     */
    async apiV1ServerUpdateInstallPost(requestParameters: ApiV1ServerUpdateInstallPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1ServerUpdateCheckGet200Response> {
        const response = await this.apiV1ServerUpdateInstallPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
